import React, { useEffect, useRef, useState } from 'react';
import { auth } from '../../lib/firebase';
import { User, LanguageCode, AppSettings, AppRoute } from '../../types';
import { getAvailableLanguages, getTranslation, useLocalization } from '../../services/i18n';
import { Smartphone, Monitor, ShieldCheck, Menu, Moon, Sun, Award, Globe, BookOpen, Radio, HeartHandshake, Info, Megaphone, MessageCircle, Search, Bell, X, Check } from 'lucide-react';

interface HeaderProps {
  currentUser: User;
  settings: AppSettings;
  activeLanguage: LanguageCode;
  onChangeLanguage: (lang: LanguageCode) => void;
  isDarkMode: boolean;
  onToggleDarkMode: () => void;
  isMobileShell: boolean;
  onToggleMobileShell: () => void;
  onOpenMenu: () => void;
  currentRoute?: AppRoute;
  onNavigate?: (route: AppRoute) => void;
}

type SearchItem={type:string;id:string;title:string;description:string;scope:string;organizationId?:string};
type NotificationItem={id:string;title?:string;message?:string;body?:string;createdAt?:unknown;read?:boolean;organizationId?:string;type?:string};

export const Header: React.FC<HeaderProps> = ({ currentUser, settings, activeLanguage, onChangeLanguage, isDarkMode, onToggleDarkMode, isMobileShell, onToggleMobileShell, onOpenMenu, currentRoute = 'home', onNavigate }) => {
  const t=(key:string,fallback?:string)=>getTranslation(key,activeLanguage,settings?.customTranslations,fallback);
  useLocalization(settings);
  const availableLanguages=getAvailableLanguages(settings);
  const isPrivileged=['super_admin','union_admin','conference_admin','district_admin','church_admin'].includes(String(currentUser.role||''))||['owner','admin'].includes(String(currentUser.organizationRole||''));
  const nav=(route:AppRoute)=>{if(onNavigate)onNavigate(route);};
  const [searchOpen,setSearchOpen]=useState(false),[searchQuery,setSearchQuery]=useState(''),[searchItems,setSearchItems]=useState<SearchItem[]>([]),[searchBusy,setSearchBusy]=useState(false);
  const [notificationsOpen,setNotificationsOpen]=useState(false),[notifications,setNotifications]=useState<NotificationItem[]>([]),[notificationBusy,setNotificationBusy]=useState(false);
  const searchRef=useRef<HTMLDivElement|null>(null),notificationRef=useRef<HTMLDivElement|null>(null);
  const getToken=async()=>auth?.currentUser?.getIdToken();
  const loadNotifications=async()=>{const token=await getToken();if(!token)return;setNotificationBusy(true);try{const response=await fetch('/api/admin/notifications?action=list',{headers:{Authorization:`Bearer ${token}`}});if(response.ok){const body=await response.json().catch(()=>({}));setNotifications(Array.isArray(body.items)?body.items:[]);}}finally{setNotificationBusy(false);}};
  useEffect(()=>{if(!searchOpen){setSearchItems([]);return;}if(searchQuery.trim().length<2){setSearchItems([]);return;}const controller=new AbortController();const timer=window.setTimeout(()=>{void(async()=>{const token=await getToken();if(!token)return;setSearchBusy(true);try{const response=await fetch(`/api/admin/search?q=${encodeURIComponent(searchQuery.trim())}&limit=12`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal});if(response.ok){const body=await response.json().catch(()=>({}));setSearchItems(Array.isArray(body.items)?body.items:[]);}else setSearchItems([]);}catch(error){if((error as Error).name!=='AbortError')setSearchItems([]);}finally{setSearchBusy(false);}})();},250);return()=>{window.clearTimeout(timer);controller.abort();};},[searchQuery,searchOpen]);
  useEffect(()=>{if(notificationsOpen)void loadNotifications();},[notificationsOpen,currentUser.uid]);
  useEffect(()=>{const close=(event:MouseEvent)=>{const target=event.target as Node;if(searchRef.current&&!searchRef.current.contains(target))setSearchOpen(false);if(notificationRef.current&&!notificationRef.current.contains(target))setNotificationsOpen(false);};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close);},[]);
  const openSearchResult=(item:SearchItem)=>{setSearchOpen(false);setSearchQuery('');if(item.type==='announcement')nav('announcements');else if(item.type==='radio')nav('radio');else if(item.type==='certificate')nav('certificates');else if(item.type==='guide'||item.type==='lesson')nav('home');else if(isPrivileged)nav('admin');};
  const markNotificationRead=async(item:NotificationItem)=>{if(item.read)return;const token=await getToken();if(!token)return;try{await fetch('/api/admin/notifications',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action:'markRead',notificationId:item.id})});setNotifications(items=>items.map(entry=>entry.id===item.id?{...entry,read:true}:entry));}catch(error){console.warn('Notification read update failed',error);}};
  const unreadCount=notifications.filter(item=>item.read!==true).length;

  return <header style={{background:'linear-gradient(135deg, var(--vop-navy-950) 0%, var(--vop-navy-900) 100%)',borderBottom:'1px solid rgba(255,255,255,.08)',color:'#fff',padding:'0.65rem 1rem',position:'sticky',top:0,zIndex:40,boxShadow:'var(--shadow-md)'}}>
    <div style={{maxWidth:'1360px',margin:'0 auto',display:'flex',alignItems:'center',justifyContent:'space-between',gap:'.75rem'}}>
      <div style={{display:'flex',alignItems:'center',gap:'.65rem',cursor:'pointer',flexShrink:0}} onClick={()=>nav('home')}><div style={{width:36,height:36,borderRadius:10,background:'rgba(255,255,255,.1)',display:'flex',alignItems:'center',justifyContent:'center',overflow:'hidden',border:'1px solid rgba(255,255,255,.2)',boxShadow:'var(--shadow-sm)'}}><img src="/assets/vop_logo_2.png" alt={t('common.app_title','Voice of Prophecy')} style={{width:26,height:26,objectFit:'contain'}} onError={(e)=>{(e.target as HTMLElement).style.display='none';}}/></div><div><div style={{display:'flex',alignItems:'center',gap:'.4rem'}}><span style={{fontWeight:800,fontSize:'1.05rem',letterSpacing:'-.01em',fontFamily:'var(--font-display)'}}>{t('common.app_title',settings.appName||'Voice of Prophecy')}</span><span className="badge badge-gold hide-sm" style={{fontSize:'.6rem',padding:'.1rem .4rem'}}>v4.0 PRO</span></div><div className="hide-sm" style={{fontSize:'.68rem',color:'rgba(255,255,255,.7)',fontWeight:500}}>{t('common.school_subtitle',settings.schoolName||'Bible Correspondence School')}</div></div></div>
      <nav aria-label={t('navigation.desktop','Desktop Navigation')} className="hidden lg:flex items-center gap-1"><button onClick={()=>nav('home')} className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all ${currentRoute==='home'?'bg-amber-400/20 text-amber-300 font-bold':'text-slate-300 hover:text-white hover:bg-white/5'}`}>{t('navigation.discover','Discover')}</button><button onClick={()=>nav('resources')} className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all flex items-center gap-1.5 ${currentRoute==='resources'?'bg-amber-400/20 text-amber-300 font-bold':'text-slate-300 hover:text-white hover:bg-white/5'}`}><BookOpen size={14}/><span>{t('navigation.library','Library')}</span></button><button onClick={()=>nav('prayer')} className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all flex items-center gap-1.5 ${currentRoute==='prayer'?'bg-amber-400/20 text-amber-300 font-bold':'text-slate-300 hover:text-white hover:bg-white/5'}`}><HeartHandshake size={14}/><span>{t('navigation.prayer','Prayer')}</span></button><button onClick={()=>nav('radio')} className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all flex items-center gap-1.5 ${currentRoute==='radio'?'bg-amber-400/20 text-amber-300 font-bold':'text-slate-300 hover:text-white hover:bg-white/5'}`}><Radio size={14}/><span>{t('navigation.radio','Radio')}</span></button><button onClick={()=>nav('announcements')} className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all flex items-center gap-1.5 ${currentRoute==='announcements'?'bg-amber-400/20 text-amber-300 font-bold':'text-slate-300 hover:text-white hover:bg-white/5'}`}><Megaphone size={14}/><span>{t('navigation.announcements','Announcements')}</span></button>{currentUser.role==='student'&&<button onClick={()=>nav('support')} className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all flex items-center gap-1.5 ${currentRoute==='support'?'bg-amber-400/20 text-amber-300 font-bold':'text-slate-300 hover:text-white hover:bg-white/5'}`}><MessageCircle size={14}/><span>{t('navigation.support','Support')}</span></button>}<button onClick={()=>nav('about')} className={`px-3 py-1.5 rounded-xl text-xs font-semibold transition-all flex items-center gap-1.5 ${currentRoute==='about'?'bg-amber-400/20 text-amber-300 font-bold':'text-slate-300 hover:text-white hover:bg-white/5'}`}><Info size={14}/><span>{t('navigation.about','About')}</span></button></nav>
      <div style={{display:'flex',alignItems:'center',gap:'.4rem',flexShrink:0}}>
        <div ref={searchRef} style={{position:'relative'}}><button onClick={()=>setSearchOpen(value=>!value)} className="btn btn-ghost" style={{color:'rgba(255,255,255,.9)',padding:'.4rem'}} title={t('common.search','Search')} aria-label={t('common.search','Search')}><Search size={17}/></button>{searchOpen&&<div style={{position:'absolute',right:0,top:'calc(100% + .5rem)',width:'min(420px,88vw)',background:'var(--bg-primary)',color:'var(--text-primary)',border:'1px solid var(--border-color)',borderRadius:14,boxShadow:'var(--shadow-lg)',padding:'.65rem',zIndex:100}}><div style={{display:'flex',alignItems:'center',gap:'.4rem',border:'1px solid var(--border-color)',borderRadius:10,padding:'.35rem .5rem'}}><Search size={15}/><input autoFocus value={searchQuery} onChange={event=>setSearchQuery(event.target.value)} placeholder={t('common.search','Search')} aria-label={t('common.search','Search')} style={{border:0,outline:0,background:'transparent',color:'inherit',width:'100%'}}/><button onClick={()=>setSearchQuery('')} aria-label={t('common.clear','Clear')} style={{border:0,background:'transparent',color:'inherit',cursor:'pointer'}}><X size={14}/></button></div><div style={{maxHeight:360,overflowY:'auto',marginTop:'.5rem'}}>{searchBusy?<div style={{padding:'.8rem',fontSize:'.8rem',opacity:.7}}>{t('common.searching','Searching…')}</div>:searchQuery.trim().length<2?<div style={{padding:'.8rem',fontSize:'.8rem',opacity:.7}}>{t('common.search_hint','Type at least 2 characters')}</div>:searchItems.length===0?<div style={{padding:'.8rem',fontSize:'.8rem',opacity:.7}}>{t('common.no_results','No results')}</div>:searchItems.map(item=><button key={`${item.type}:${item.id}`} onClick={()=>openSearchResult(item)} style={{display:'block',width:'100%',textAlign:'left',border:0,background:'transparent',padding:'.55rem',borderRadius:9,color:'inherit',cursor:'pointer'}}><div style={{fontWeight:700,fontSize:'.82rem'}}>{item.title}</div><div style={{fontSize:'.68rem',opacity:.65}}>{item.type} · {item.description}</div></button>)}</div></div>}</div>
        <div ref={notificationRef} style={{position:'relative'}}><button onClick={()=>setNotificationsOpen(value=>!value)} className="btn btn-ghost" style={{color:'rgba(255,255,255,.9)',padding:'.4rem',position:'relative'}} title={t('common.notifications','Notifications')} aria-label={t('common.notifications','Notifications')}><Bell size={17}/>{unreadCount>0&&<span aria-label={`${unreadCount} ${t('common.unread','unread')}`} style={{position:'absolute',right:1,top:1,minWidth:15,height:15,padding:'0 3px',borderRadius:999,background:'var(--vop-gold-500)',color:'#0b2244',fontSize:'.55rem',fontWeight:800,display:'flex',alignItems:'center',justifyContent:'center'}}>{unreadCount>9?'9+':unreadCount}</span>}</button>{notificationsOpen&&<div style={{position:'absolute',right:0,top:'calc(100% + .5rem)',width:'min(380px,88vw)',background:'var(--bg-primary)',color:'var(--text-primary)',border:'1px solid var(--border-color)',borderRadius:14,boxShadow:'var(--shadow-lg)',padding:'.65rem',zIndex:100}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'.2rem .3rem .5rem'}}><strong style={{fontSize:'.85rem'}}>{t('common.notifications','Notifications')}</strong><span style={{fontSize:'.68rem',opacity:.65}}>{unreadCount}</span></div><div style={{maxHeight:360,overflowY:'auto'}}>{notificationBusy?<div style={{padding:'.8rem',fontSize:'.8rem',opacity:.7}}>{t('common.loading','Loading…')}</div>:notifications.length===0?<div style={{padding:'.8rem',fontSize:'.8rem',opacity:.7}}>{t('common.no_notifications','No notifications')}</div>:notifications.slice(0,30).map(item=><button key={item.id} onClick={()=>void markNotificationRead(item)} style={{display:'flex',gap:'.5rem',width:'100%',textAlign:'left',border:0,borderRadius:9,background:item.read?'transparent':'rgba(245,180,50,.08)',padding:'.6rem',color:'inherit',cursor:'pointer'}}><span style={{marginTop:'.15rem',opacity:item.read?.45:1}}>{item.read?<Check size={14}/>:<Bell size={14}/>}</span><span style={{minWidth:0}}><span style={{display:'block',fontWeight:item.read?600:800,fontSize:'.78rem'}}>{item.title||item.type||t('common.notification','Notification')}</span><span style={{display:'block',fontSize:'.68rem',opacity:.7,whiteSpace:'normal'}}>{item.message||item.body||''}</span></span></button>)}</div></div>}</div>
        <div style={{position:'relative',display:'flex',alignItems:'center'}}><div style={{display:'flex',alignItems:'center',gap:'.25rem',background:'rgba(255,255,255,.08)',border:'1px solid rgba(255,255,255,.15)',borderRadius:'var(--radius-full)',padding:'.25rem .5rem',fontSize:'.75rem',color:'#fff'}}><Globe size={13} color="var(--vop-gold-400)"/><select value={activeLanguage} onChange={e=>onChangeLanguage(e.target.value as LanguageCode)} style={{background:'transparent',border:'none',color:'#fff',outline:'none',fontWeight:600,fontSize:'.75rem',cursor:'pointer',maxWidth:'160px'}}>{availableLanguages.map(lang=><option key={lang.code} value={lang.code} style={{background:'#0b2244',color:'#fff'}}>{lang.name}{lang.nativeName&&lang.nativeName.toLowerCase()!==lang.name.toLowerCase()?` (${lang.nativeName})`:''}</option>)}</select></div></div>
        <button onClick={()=>nav('certificates')} className="btn btn-gold hide-sm" title={t('navigation.certificate','Certificate')} style={{padding:'.35rem .75rem',fontSize:'.75rem',borderRadius:'var(--radius-full)'}}><Award size={14}/><span>{t('navigation.certificate','Certificate')}</span></button>{isPrivileged&&<button onClick={()=>nav('admin')} className="btn btn-outline hide-sm" title={t('navigation.admin','Admin Panel')} style={{borderColor:'rgba(255,255,255,.25)',color:'#fff',padding:'.35rem .75rem',fontSize:'.75rem',borderRadius:'var(--radius-full)'}}><ShieldCheck size={14} color="var(--vop-gold-400)"/><span>{t('admin_panel','Admin Panel')}</span></button>}
        <button onClick={onToggleMobileShell} className="btn btn-ghost hide-sm" style={{color:'rgba(255,255,255,.85)',padding:'.4rem'}} title={isMobileShell?t('common.desktop_view','Switch to Full Desktop View'):t('common.mobile_view','Simulate Phone Shell')}>{isMobileShell?<Monitor size={16}/>:<Smartphone size={16}/>}</button><button onClick={onToggleDarkMode} className="btn btn-ghost" style={{color:'rgba(255,255,255,.85)',padding:'.4rem'}} title={isDarkMode?t('common.light_mode','Light Mode'):t('common.dark_mode','Dark Mode')}>{isDarkMode?<Sun size={16}/>:<Moon size={16}/>}</button>
        <button onClick={()=>nav('profile')} className="hide-sm" style={{display:'flex',alignItems:'center',gap:'.4rem',background:'rgba(255,255,255,.08)',border:'1px solid rgba(255,255,255,.15)',borderRadius:'var(--radius-full)',padding:'.2rem .5rem .2rem .2rem',cursor:'pointer',color:'#fff'}} title={t('common.manage_profile','Manage Profile & Church')}><div style={{width:26,height:26,borderRadius:'50%',background:'linear-gradient(135deg,var(--vop-gold-500),var(--vop-gold-600))',display:'flex',alignItems:'center',justifyContent:'center',overflow:'hidden',fontWeight:700,fontSize:'.78rem',color:'#0b2244'}}>{currentUser.displayName.charAt(0)}</div><span style={{fontSize:'.75rem',fontWeight:600,maxWidth:90,overflow:'hidden',textOverflow:'ellipsis'}}>{currentUser.displayName.split(' ')[0]}</span></button>
        <button onClick={onOpenMenu} className="btn btn-ghost" style={{color:'rgba(255,255,255,.85)',padding:'.4rem'}} title={t('common.open_menu','Open Menu')}><Menu size={18}/></button>
      </div>
    </div>
  </header>;
};
