import React, { useEffect, useMemo, useState } from 'react';
import type { AppSettings, ChurchOrganization, Conference, DiscoverGuide, District, LanguageCode, Lesson, Union, User, UserRole } from '../types';
import { exportAdminBackup, loadAdminData, saveAdminSettings, saveTranslation, saveAdminUser, saveGuide, deleteGuide as deleteFirestoreGuide, saveLesson, deleteLesson, saveOrganization, deleteOrganization, type AdminDataSnapshot } from '../services/adminFirestore';
import { MASTER_TRANSLATION_KEYS, DEFAULT_TRANSLATIONS } from '../services/i18n';
import { ArrowLeft, BookOpen, ChevronDown, ChevronUp, Database, Edit3, Globe, LogOut, Plus, Save, Shield, Settings, Trash2, Users, X } from 'lucide-react';
import { signOut } from 'firebase/auth';
import { auth } from '../lib/firebase';
import '../styles/admin-command-center.css';

interface AdminPageProps { currentUser: User; activeLanguage: LanguageCode; onBack: () => void; }
type Tab = 'candidates' | 'curriculum' | 'languages' | 'branding' | 'backup' | 'roles' | 'hierarchy';
const ROLE_LABELS: Record<UserRole, string> = { super_admin:'Super Admin', union_admin:'Union Admin', conference_admin:'Conference Admin', district_admin:'District Admin', church_admin:'Church Admin', student:'Student' };

function emptySettings(): AppSettings {
  return { appName:'Voice of Prophecy', organizationName:'Seventh-day Adventist Church', schoolName:'Bible Correspondence School', directorName:'', directorTitle:'', contactPhone:'', whatsappNumber:'', contactEmail:'', quizPassThreshold:80, defaultLanguage:'en', detailPages:{aboutUsMission:'',aboutUsHistory:'',aboutUsLeadership:'',aboutAppDescription:'',aboutAppVersion:'',aboutAppCredits:'',contactOfficeAddress:'',contactOfficeHours:'',contactPhoneNumbers:[],contactEmails:[],contactWhatsAppNumbers:[],socialLinks:{}} };
}
function emptyGuide(language:string):DiscoverGuide { return { id:`discover-${language}-${Date.now()}`, discoverNumber:1, title:'', subtitle:'', description:'', language, image:'', certificateEligible:true, lessons:[] }; }
function emptyLesson():Lesson { return { id:`lesson-${Date.now()}`, title:'', lessonNumber:'', description:'', type:'Lesson', estimatedMinutes:15, contentPages:[], questions:[] }; }

export const AdminPage: React.FC<AdminPageProps> = ({ currentUser, activeLanguage, onBack }) => {
  const [tab,setTab]=useState<Tab>('candidates'), [snapshot,setSnapshot]=useState<AdminDataSnapshot|null>(null), [loading,setLoading]=useState(true), [saving,setSaving]=useState(false), [message,setMessage]=useState(''), [error,setError]=useState(''), [search,setSearch]=useState('');
  const [settingsDraft,setSettingsDraft]=useState<AppSettings>(emptySettings()), [translationLanguage,setTranslationLanguage]=useState(activeLanguage||'bem'), [translationDraft,setTranslationDraft]=useState<Record<string,string>>({});
  const [guideEditor,setGuideEditor]=useState<DiscoverGuide|null>(null), [lessonEditor,setLessonEditor]=useState<{language:string;lesson:Lesson}|null>(null), [openGuide,setOpenGuide]=useState<string|null>(null);
  const [newOrgType,setNewOrgType]=useState<'unions'|'conferences'|'districts'|'churches'>('churches'), [newOrg,setNewOrg]=useState<Record<string,string>>({});
  const isSuperAdmin=currentUser.role==='super_admin';

  const reload=async()=>{setLoading(true);setError('');try{const data=await loadAdminData();setSnapshot(data);setSettingsDraft(data.settings);setTranslationDraft(data.translations[translationLanguage]||{});}catch(e){setError(e instanceof Error?e.message:'Management data could not be loaded from Firestore.');}finally{setLoading(false);}};
  useEffect(()=>{void reload();},[]);
  useEffect(()=>{if(snapshot)setTranslationDraft(snapshot.translations[translationLanguage]||{});},[translationLanguage,snapshot]);

  const users=snapshot?.users||[], guides=snapshot?.guides||[];
  const students=useMemo(()=>users.filter(u=>!u.role||u.role==='student'),[users]);
  const admins=useMemo(()=>users.filter(u=>u.role&&u.role!=='student'),[users]);
  const filteredStudents=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return students;return students.filter(u=>[u.displayName,u.email,u.phoneNumber,u.churchId,u.districtId,u.conferenceId].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)));},[students,search]);
  const languages=useMemo(()=>{const s=new Set<string>(guides.map(g=>g.language).filter(Boolean));Object.keys(snapshot?.translations||{}).forEach(code=>s.add(code));if(activeLanguage)s.add(activeLanguage);return [...s].sort();},[guides,snapshot?.translations,activeLanguage]);

  const save=async(action:()=>Promise<void>,success:string)=>{setSaving(true);setError('');setMessage('');try{await action();setMessage(success);await reload();}catch(e){setError(e instanceof Error?e.message:'The requested change could not be saved.');}finally{setSaving(false);}};
  const handleLogout=async()=>{if(auth)await signOut(auth);};
  const updateUserLocal=(user:User,patch:Partial<User>)=>setSnapshot(s=>s?{...s,users:s.users.map(x=>x.uid===user.uid?{...x,...patch}:x)}:s);
  const saveUser=async(user:User)=>save(()=>saveAdminUser(user),'User profile saved to Firestore.');
  const saveGuideEditor=async()=>{if(!guideEditor?.title.trim()||!guideEditor.language.trim()){setError('Guide title and language are required.');return;}await save(()=>saveGuide(guideEditor),'Guide saved to Firestore.');setGuideEditor(null);};
  const removeGuide=async(g:DiscoverGuide)=>{if(!confirm(`Delete "${g.title}" and all of its lessons from Firestore?`))return;await save(()=>deleteFirestoreGuide(g),'Guide and its lessons deleted from Firestore.');};
  const saveLessonEditor=async()=>{if(!lessonEditor||!lessonEditor.lesson.title.trim()||!lessonEditor.lesson.lessonNumber.trim()){setError('Lesson title and lesson number are required.');return;}await save(()=>saveLesson(lessonEditor.language,lessonEditor.lesson),'Lesson saved to Firestore.');setLessonEditor(null);};
  const removeLesson=async(language:string,l:Lesson)=>{if(!confirm(`Delete lesson "${l.title}"?`))return;await save(()=>deleteLesson(language,l.id),'Lesson deleted from Firestore.');};
  const updatePage=(i:number,patch:Partial<NonNullable<Lesson['contentPages']>[number]>)=>{if(!lessonEditor)return;const p=[...(lessonEditor.lesson.contentPages||[])];p[i]={...p[i],...patch};setLessonEditor({...lessonEditor,lesson:{...lessonEditor.lesson,contentPages:p}});};
  const addPage=()=>{if(!lessonEditor)return;const p=[...(lessonEditor.lesson.contentPages||[])];p.push({pageNumber:p.length+1,title:'',content:''});setLessonEditor({...lessonEditor,lesson:{...lessonEditor.lesson,contentPages:p}});};
  const removePage=(i:number)=>{if(!lessonEditor)return;const p=(lessonEditor.lesson.contentPages||[]).filter((_,x)=>x!==i).map((x,n)=>({...x,pageNumber:n+1}));setLessonEditor({...lessonEditor,lesson:{...lessonEditor.lesson,contentPages:p}});};
  const updateAdminRole=(u:User,role:UserRole,nodeType:User['adminNodeType'],nodeId:string)=>updateUserLocal(u,{role,adminNodeType:nodeType,adminNodeId:nodeId||undefined,privileges:{...u.privileges,admin:true,superAdmin:role==='super_admin',editor:role==='super_admin'||u.privileges.editor,manager:true}});
  const saveSettings=async()=>{if(isSuperAdmin)await save(()=>saveAdminSettings(settingsDraft),'Ministry settings saved to Firestore.');};
  const saveTranslations=async()=>save(()=>saveTranslation(translationLanguage,translationDraft),'Translations saved to Firestore.');
  const createOrg=async()=>{const id=newOrg.id?.trim(),name=newOrg.name?.trim();if(!id||!name){setError('Organization ID and name are required.');return;}try{const extra=newOrg.json?JSON.parse(newOrg.json):{};await saveOrganization(newOrgType,id,{...extra,...newOrg,id,name} as Union&Conference&District&ChurchOrganization);setNewOrg({});await reload();setMessage('Organization saved to Firestore.');}catch(e){setError(e instanceof Error?e.message:'Invalid organization data.');}};
  const removeOrg=async(type:'unions'|'conferences'|'districts'|'churches',id:string)=>{if(!isSuperAdmin||!confirm('Delete this organization from Firestore?'))return;await save(()=>deleteOrganization(type,id),'Organization deleted from Firestore.');};
  const exportBackup=async()=>{if(!snapshot)return;const json=await exportAdminBackup(snapshot);const blob=new Blob([json],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`VOP-Firestore-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);};

  const filteredTranslationKeys=MASTER_TRANSLATION_KEYS.filter(({key,defaultEn})=>{const q=search.toLowerCase().trim();return !q||key.toLowerCase().includes(q)||defaultEn.toLowerCase().includes(q);});
  const tabs:Array<[Tab,string,React.ReactNode]>=[['candidates',`Candidates (${students.length})`,<Users size={15}/>],['curriculum',`Curriculum Studio (${guides.length} Guides)`,<BookOpen size={15}/>],['languages',`Languages & Translations (${languages.length})`,<Globe size={15}/>],['branding','Ministry Branding & Setup',<Settings size={15}/>],['backup','Database & Backup',<Database size={15}/>],['roles',`Admin Roles (${admins.length})`,<Shield size={15}/>],['hierarchy','Hierarchy & Flow',<ChevronDown size={15}/>]];

  const renderCandidates=()=> <><div className="vop-admin-heading"><div><h2>Candidates & Users</h2><p>Only Firebase-authenticated users and their Firestore profiles appear here.</p></div><input className="vop-admin-input vop-admin-search" placeholder="Search name, email, phone or organization…" value={search} onChange={e=>setSearch(e.target.value)}/></div>
    <div className="vop-admin-grid" style={{marginBottom:18}}><div className="vop-admin-card"><div className="vop-admin-muted">Registered users</div><div className="vop-admin-stat">{users.length}</div></div><div className="vop-admin-card"><div className="vop-admin-muted">Students / candidates</div><div className="vop-admin-stat">{students.length}</div></div><div className="vop-admin-card"><div className="vop-admin-muted">Administrators</div><div className="vop-admin-stat">{admins.length}</div></div></div>
    <div className="vop-admin-tablewrap"><table className="vop-admin-table"><thead><tr><th>User</th><th>Contact</th><th>Organization</th><th>Progress</th><th>Status</th><th>Save</th></tr></thead><tbody>{filteredStudents.map(u=><tr key={u.uid}><td><strong>{u.displayName||'Unnamed user'}</strong><div className="vop-admin-muted">{u.uid}</div></td><td>{u.email}<br/>{u.phoneNumber||'No phone recorded'}</td><td>{u.churchId||'Unassigned'}<br/><span className="vop-admin-muted">{u.districtId||'—'} / {u.conferenceId||'—'}</span></td><td>{u.progress?.discoverProgress??0}%<br/><span className="vop-admin-muted">{u.progress?.completedLessons?.length??0} lessons</span></td><td>{u.information?.graduated?'Graduated':u.information?.graduating?'Graduating':'Student'}</td><td><button className="vop-admin-btn primary" disabled={saving} onClick={()=>void saveUser(u)}><Save size={13}/>Save</button></td></tr>)}</tbody></table></div>
    {filteredStudents.map(u=><div className="vop-admin-card" key={`edit-${u.uid}`} style={{marginTop:10}}><div className="vop-admin-heading" style={{marginBottom:10}}><div><h3>{u.displayName||'Unnamed user'}</h3><div className="vop-admin-muted">{u.email}</div></div></div><div className="vop-admin-formgrid"><label><span className="vop-admin-label">Display name</span><input className="vop-admin-input" value={u.displayName||''} onChange={e=>updateUserLocal(u,{displayName:e.target.value})}/></label><label><span className="vop-admin-label">Phone</span><input className="vop-admin-input" value={u.phoneNumber||''} onChange={e=>updateUserLocal(u,{phoneNumber:e.target.value||undefined})}/></label><label><span className="vop-admin-label">Church ID</span><input className="vop-admin-input" value={u.churchId||''} onChange={e=>updateUserLocal(u,{churchId:e.target.value||undefined})}/></label><label><span className="vop-admin-label">District ID</span><input className="vop-admin-input" value={u.districtId||''} onChange={e=>updateUserLocal(u,{districtId:e.target.value||undefined})}/></label><label><span className="vop-admin-label">Conference ID</span><input className="vop-admin-input" value={u.conferenceId||''} onChange={e=>updateUserLocal(u,{conferenceId:e.target.value||undefined})}/></label><label><span className="vop-admin-label">Status</span><select className="vop-admin-select" value={u.information?.graduated?'graduated':u.information?.graduating?'graduating':'student'} onChange={e=>updateUserLocal(u,{information:{...u.information,graduated:e.target.value==='graduated',graduating:e.target.value==='graduating'}})}><option value="student">Student</option><option value="graduating">Graduating</option><option value="graduated">Graduated</option></select></label></div><button className="vop-admin-btn primary" style={{marginTop:10}} disabled={saving} onClick={()=>void saveUser(u)}><Save size={13}/>Save profile</button></div>)}
    {!filteredStudents.length&&<div className="vop-admin-empty">No Firebase user profiles match the current filter.</div>}</>;

  const renderCurriculum=()=> <><div className="vop-admin-heading"><div><h2>Curriculum Studio</h2><p>Create and edit guides and every lesson page directly in Firestore.</p></div><div className="vop-admin-actions"><button className="vop-admin-btn gold" onClick={()=>setGuideEditor(emptyGuide(activeLanguage||languages[0]||''))}><Plus size={15}/>Add Guide</button><button className="vop-admin-btn" onClick={()=>void reload()}><Database size={15}/>Refresh</button></div></div>{!guides.length&&<div className="vop-admin-empty">No guides are configured in Firestore. Add the first guide to begin publishing curriculum.</div>}<div style={{display:'grid',gap:12}}>{guides.map(g=>{const expanded=openGuide===g.id;return <div className="vop-admin-guide" key={g.id}><div className="vop-admin-guide-head"><div><div style={{display:'flex',gap:7,flexWrap:'wrap',marginBottom:7}}><span className="vop-admin-pill">{g.language.toUpperCase()}</span><span className="vop-admin-pill">Guide {g.discoverNumber}</span><span className="vop-admin-pill">{g.lessons.length} lessons</span></div><div className="vop-admin-guide-title">{g.title||'Untitled guide'}</div><div className="vop-admin-muted">{g.description||'No description configured.'}</div></div><div className="vop-admin-actions"><button className="vop-admin-btn" onClick={()=>setGuideEditor({...g,lessons:[...g.lessons]})}><Edit3 size={14}/>Edit</button><button className="vop-admin-btn danger" onClick={()=>void removeGuide(g)}><Trash2 size={14}/>Delete</button><button className="vop-admin-btn" onClick={()=>setOpenGuide(expanded?null:g.id)}>{expanded?<ChevronUp size={14}/>:<ChevronDown size={14}/>}Lessons</button></div></div>{expanded&&<div className="vop-admin-lessons"><div className="vop-admin-actions" style={{marginBottom:10}}><button className="vop-admin-btn primary" onClick={()=>setLessonEditor({language:g.language,lesson:emptyLesson()})}><Plus size={14}/>Add Lesson</button></div>{g.lessons.map(l=><div className="vop-admin-lesson" key={l.id}><div><strong>{l.lessonNumber} — {l.title||'Untitled lesson'}</strong><div className="vop-admin-muted">{l.type} · {l.estimatedMinutes} minutes · {(l.contentPages||[]).length} pages</div></div><div className="vop-admin-actions"><button className="vop-admin-btn" onClick={()=>setLessonEditor({language:g.language,lesson:JSON.parse(JSON.stringify(l))})}><Edit3 size={13}/>Edit</button><button className="vop-admin-btn danger" onClick={()=>void removeLesson(g.language,l)}><Trash2 size={13}/></button></div></div>)}{!g.lessons.length&&<div className="vop-admin-empty">This guide has no lessons yet.</div>}</div>}</div>})}</div></>;

  const renderLanguages=()=> <><div className="vop-admin-heading"><div><h2>Language & Localization Studio</h2><p>Translations are stored in Firestore.</p></div><div className="vop-admin-actions"><input className="vop-admin-input" style={{width:180}} placeholder="Filter keys…" value={search} onChange={e=>setSearch(e.target.value)}/><select className="vop-admin-select" style={{width:120}} value={translationLanguage} onChange={e=>setTranslationLanguage(e.target.value)}>{languages.map(c=><option key={c} value={c}>{c.toUpperCase()}</option>)}</select><button className="vop-admin-btn primary" onClick={()=>void saveTranslations()} disabled={saving}><Save size={14}/>Save</button></div></div><div className="vop-admin-tablewrap"><table className="vop-admin-table"><thead><tr><th>Translation key</th><th>English reference</th><th>Translation</th></tr></thead><tbody>{filteredTranslationKeys.map(({key,defaultEn})=><tr key={key}><td><code>{key}</code></td><td>{defaultEn}</td><td><input className="vop-admin-input" value={translationDraft[key]??DEFAULT_TRANSLATIONS[translationLanguage]?.[key]??''} onChange={e=>setTranslationDraft(d=>({...d,[key]:e.target.value}))}/></td></tr>)}</tbody></table></div></>;

  const renderBranding=()=> <><div className="vop-admin-heading"><div><h2>Ministry Branding & Setup</h2><p>Global configuration is persisted in Firestore.</p></div><button className="vop-admin-btn primary" disabled={!isSuperAdmin||saving} onClick={()=>void saveSettings()}><Save size={14}/>Save settings</button></div>{!isSuperAdmin&&<div className="vop-admin-alert">Only Super Admin can change global ministry settings.</div>}<div className="vop-admin-formgrid">{(['appName','organizationName','schoolName','directorName','directorTitle','contactPhone','whatsappNumber','contactEmail'] as const).map(k=><label key={k}><span className="vop-admin-label">{k}</span><input className="vop-admin-input" disabled={!isSuperAdmin} value={String(settingsDraft[k]??'')} onChange={e=>setSettingsDraft({...settingsDraft,[k]:e.target.value})}/></label>)}<label><span className="vop-admin-label">Quiz pass threshold (%)</span><input className="vop-admin-input" type="number" min="0" max="100" disabled={!isSuperAdmin} value={settingsDraft.quizPassThreshold} onChange={e=>setSettingsDraft({...settingsDraft,quizPassThreshold:Number(e.target.value)})}/></label><label><span className="vop-admin-label">Default language</span><select className="vop-admin-select" disabled={!isSuperAdmin} value={settingsDraft.defaultLanguage} onChange={e=>setSettingsDraft({...settingsDraft,defaultLanguage:e.target.value})}>{languages.map(c=><option key={c}>{c}</option>)}</select></label><label className="vop-admin-full"><span className="vop-admin-label">About / mission</span><textarea className="vop-admin-textarea" disabled={!isSuperAdmin} value={settingsDraft.detailPages?.aboutUsMission||''} onChange={e=>setSettingsDraft({...settingsDraft,detailPages:{...settingsDraft.detailPages!,aboutUsMission:e.target.value}})}/></label><label className="vop-admin-full"><span className="vop-admin-label">About / history</span><textarea className="vop-admin-textarea" disabled={!isSuperAdmin} value={settingsDraft.detailPages?.aboutUsHistory||''} onChange={e=>setSettingsDraft({...settingsDraft,detailPages:{...settingsDraft.detailPages!,aboutUsHistory:e.target.value}})}/></label><label className="vop-admin-full"><span className="vop-admin-label">About / leadership</span><textarea className="vop-admin-textarea" disabled={!isSuperAdmin} value={settingsDraft.detailPages?.aboutUsLeadership||''} onChange={e=>setSettingsDraft({...settingsDraft,detailPages:{...settingsDraft.detailPages!,aboutUsLeadership:e.target.value}})}/></label></div></>;

  const renderRoles=()=> <><div className="vop-admin-heading"><div><h2>Admin Roles & Access</h2><p>Manage existing authenticated users. No demo accounts are created here.</p></div></div><div className="vop-admin-tablewrap"><table className="vop-admin-table"><thead><tr><th>User</th><th>Role</th><th>Node type</th><th>Node ID</th><th>Privileges</th><th>Save</th></tr></thead><tbody>{admins.map(u=><tr key={u.uid}><td><strong>{u.displayName}</strong><div className="vop-admin-muted">{u.email}</div></td><td><select className="vop-admin-select" disabled={!isSuperAdmin} value={u.role} onChange={e=>updateAdminRole(u,e.target.value as UserRole,u.adminNodeType,u.adminNodeId||'')}>{Object.entries(ROLE_LABELS).filter(([r])=>r!=='student').map(([r,l])=><option key={r} value={r}>{l}</option>)}</select></td><td><select className="vop-admin-select" disabled={!isSuperAdmin} value={u.adminNodeType||'super'} onChange={e=>updateAdminRole(u,u.role as UserRole,e.target.value as User['adminNodeType'],u.adminNodeId||'')}><option value="super">Super</option><option value="union">Union</option><option value="conference">Conference</option><option value="district">District</option><option value="church">Church</option></select></td><td><input className="vop-admin-input" disabled={!isSuperAdmin} value={u.adminNodeId||''} onChange={e=>updateUserLocal(u,{adminNodeId:e.target.value||undefined})}/></td><td>{u.privileges?.editor?'Editor':'Manager'}{u.privileges?.developer?' · Developer':''}</td><td><button className="vop-admin-btn primary" disabled={!isSuperAdmin||saving} onClick={()=>void saveUser(u)}><Save size={13}/>Save</button></td></tr>)}</tbody></table></div>{!admins.length&&<div className="vop-admin-empty">No administrator profiles are configured in Firestore.</div>}</>;

  const renderHierarchy=()=>{const lists=[['unions',snapshot?.unions||[]],['conferences',snapshot?.conferences||[]],['districts',snapshot?.districts||[]],['churches',snapshot?.churches||[]]] as const;return <><div className="vop-admin-heading"><div><h2>Hierarchy & Flow</h2><p>Organizational records are read from and written to Firestore.</p></div></div>{isSuperAdmin&&<div className="vop-admin-card"><div className="vop-admin-section-title">Add organization record</div><div className="vop-admin-formgrid three"><label><span className="vop-admin-label">Collection</span><select className="vop-admin-select" value={newOrgType} onChange={e=>setNewOrgType(e.target.value as typeof newOrgType)}><option value="churches">Churches</option><option value="districts">Districts</option><option value="conferences">Conferences</option><option value="unions">Unions</option></select></label><label><span className="vop-admin-label">Document ID</span><input className="vop-admin-input" value={newOrg.id||''} onChange={e=>setNewOrg({...newOrg,id:e.target.value})}/></label><label><span className="vop-admin-label">Name</span><input className="vop-admin-input" value={newOrg.name||''} onChange={e=>setNewOrg({...newOrg,name:e.target.value})}/></label><label className="vop-admin-full"><span className="vop-admin-label">Additional fields (JSON)</span><textarea className="vop-admin-textarea" value={newOrg.json||''} placeholder='{"code":"...","conferenceId":"..."}' onChange={e=>setNewOrg({...newOrg,json:e.target.value})}/></label></div><button className="vop-admin-btn primary" onClick={()=>void createOrg()}><Save size={14}/>Save organization</button></div>}<div className="vop-admin-grid" style={{marginTop:14}}>{lists.map(([type,list])=><div className="vop-admin-card" key={type}><h3>{type[0].toUpperCase()+type.slice(1)}</h3><div className="vop-admin-stat">{list.length}</div><div className="vop-admin-muted">Firestore records</div><div style={{marginTop:10,display:'grid',gap:6}}>{list.map((item:any)=><div key={item.id} className="vop-admin-pill" style={{justifyContent:'space-between'}}><span>{item.name||item.id}</span>{isSuperAdmin&&<button className="vop-admin-btn danger" style={{padding:'3px 6px'}} onClick={()=>void removeOrg(type,item.id)}><Trash2 size={11}/></button>}</div>)}</div></div>)}</div></>};

  const renderBackup=()=> <><div className="vop-admin-heading"><div><h2>Database & Backup</h2><p>Export the current Firestore management snapshot.</p></div><button className="vop-admin-btn gold" onClick={()=>void exportBackup()} disabled={!snapshot}><Database size={14}/>Export snapshot</button></div><div className="vop-admin-alert">Export is read-only in the browser. Bulk restore is intentionally not exposed as a client-side overwrite.</div>{snapshot&&<div className="vop-admin-grid" style={{marginTop:14}}>{[['Users',snapshot.users.length],['Guides',snapshot.guides.length],['Lessons',snapshot.guides.reduce((n,g)=>n+g.lessons.length,0)],['Languages',languages.length],['Unions',snapshot.unions.length],['Conferences',snapshot.conferences.length],['Districts',snapshot.districts.length],['Churches',snapshot.churches.length]].map(([l,n])=><div className="vop-admin-card" key={String(l)}><div className="vop-admin-muted">{l}</div><div className="vop-admin-stat">{n}</div></div>)}</div>}</>;

  if(loading&&!snapshot)return <div className="vop-admin-page"><div className="vop-admin-shell"><div className="vop-admin-body"><div className="vop-admin-empty">Loading live VOP management data from Firestore…</div></div></div></div>;

  return <div className="vop-admin-page"><div className="vop-admin-shell">
    <header className="vop-admin-top"><div className="vop-admin-toprow"><div className="vop-admin-brand"><button className="vop-admin-close" type="button" onClick={onBack} title="Back"><ArrowLeft size={19}/></button><div className="vop-admin-brand-logo"><img src="/assets/vop_logo_2.png" alt="VOP"/></div><div><div className="vop-admin-title">Admin & Ministry Command Center</div><div className="vop-admin-subtitle">{settingsDraft.schoolName} • {settingsDraft.organizationName}</div></div></div><button className="vop-admin-close" type="button" onClick={()=>void handleLogout()} title="Log out"><LogOut size={18}/></button></div><div className="vop-admin-tabs" role="tablist">{tabs.map(([k,label,icon])=><button key={k} className={`vop-admin-tab ${tab===k?'active':''}`} onClick={()=>setTab(k)} type="button">{icon}{label}</button>)}</div></header>
    <main className="vop-admin-body">{message&&<div className="vop-admin-alert" style={{marginBottom:12}}>{message}</div>}{error&&<div className="vop-admin-alert error" style={{marginBottom:12}}>{error}</div>}{tab==='candidates'&&renderCandidates()}{tab==='curriculum'&&renderCurriculum()}{tab==='languages'&&renderLanguages()}{tab==='branding'&&renderBranding()}{tab==='backup'&&renderBackup()}{tab==='roles'&&renderRoles()}{tab==='hierarchy'&&renderHierarchy()}</main>
  </div>

  {guideEditor&&<div className="vop-admin-modal" role="dialog" aria-modal="true"><div className="vop-admin-modal-panel"><div className="vop-admin-modal-head"><h3>{guides.some(g=>g.id===guideEditor.id)?'Edit Guide':'Create Guide'}</h3><button className="vop-admin-close" onClick={()=>setGuideEditor(null)}><X size={17}/></button></div><div className="vop-admin-modal-body"><div className="vop-admin-formgrid"><label><span className="vop-admin-label">Language code</span><input className="vop-admin-input" value={guideEditor.language} onChange={e=>setGuideEditor({...guideEditor,language:e.target.value.toLowerCase()})}/></label><label><span className="vop-admin-label">Guide number</span><input className="vop-admin-input" type="number" value={guideEditor.discoverNumber} onChange={e=>setGuideEditor({...guideEditor,discoverNumber:Number(e.target.value)})}/></label><label><span className="vop-admin-label">Title</span><input className="vop-admin-input" value={guideEditor.title} onChange={e=>setGuideEditor({...guideEditor,title:e.target.value})}/></label><label><span className="vop-admin-label">Subtitle</span><input className="vop-admin-input" value={guideEditor.subtitle} onChange={e=>setGuideEditor({...guideEditor,subtitle:e.target.value})}/></label><label className="vop-admin-full"><span className="vop-admin-label">Description</span><textarea className="vop-admin-textarea" value={guideEditor.description} onChange={e=>setGuideEditor({...guideEditor,description:e.target.value})}/></label><label><span className="vop-admin-label">Cover image URL / path</span><input className="vop-admin-input" value={guideEditor.image} onChange={e=>setGuideEditor({...guideEditor,image:e.target.value})}/></label><label><span className="vop-admin-label">Certificate eligible</span><select className="vop-admin-select" value={String(guideEditor.certificateEligible)} onChange={e=>setGuideEditor({...guideEditor,certificateEligible:e.target.value==='true'})}><option value="true">Yes</option><option value="false">No</option></select></label></div><div className="vop-admin-actions" style={{marginTop:16}}><button className="vop-admin-btn primary" disabled={saving} onClick={()=>void saveGuideEditor()}><Save size={14}/>Save Guide</button><button className="vop-admin-btn" onClick={()=>setGuideEditor(null)}>Cancel</button></div></div></div></div>}

  {lessonEditor&&<div className="vop-admin-modal" role="dialog" aria-modal="true"><div className="vop-admin-modal-panel"><div className="vop-admin-modal-head"><h3>Edit Lesson</h3><button className="vop-admin-close" onClick={()=>setLessonEditor(null)}><X size={17}/></button></div><div className="vop-admin-modal-body"><div className="vop-admin-formgrid"><label><span className="vop-admin-label">Lesson ID</span><input className="vop-admin-input" value={lessonEditor.lesson.id} onChange={e=>setLessonEditor({...lessonEditor,lesson:{...lessonEditor.lesson,id:e.target.value}})}/></label><label><span className="vop-admin-label">Lesson number</span><input className="vop-admin-input" value={lessonEditor.lesson.lessonNumber} onChange={e=>setLessonEditor({...lessonEditor,lesson:{...lessonEditor.lesson,lessonNumber:e.target.value}})}/></label><label><span className="vop-admin-label">Title</span><input className="vop-admin-input" value={lessonEditor.lesson.title} onChange={e=>setLessonEditor({...lessonEditor,lesson:{...lessonEditor.lesson,title:e.target.value}})}/></label><label><span className="vop-admin-label">Type</span><select className="vop-admin-select" value={lessonEditor.lesson.type} onChange={e=>setLessonEditor({...lessonEditor,lesson:{...lessonEditor.lesson,type:e.target.value as Lesson['type']}})}><option>Lesson</option><option>Test</option></select></label><label><span className="vop-admin-label">Estimated minutes</span><input className="vop-admin-input" type="number" min="1" value={lessonEditor.lesson.estimatedMinutes} onChange={e=>setLessonEditor({...lessonEditor,lesson:{...lessonEditor.lesson,estimatedMinutes:Number(e.target.value)}})}/></label><label className="vop-admin-full"><span className="vop-admin-label">Description</span><textarea className="vop-admin-textarea" value={lessonEditor.lesson.description} onChange={e=>setLessonEditor({...lessonEditor,lesson:{...lessonEditor.lesson,description:e.target.value}})}/></label></div>
    <div className="vop-admin-section"><div className="vop-admin-section-title">Lesson pages <button className="vop-admin-btn" onClick={addPage}><Plus size={13}/>Add page</button></div>{(lessonEditor.lesson.contentPages||[]).map((page,i)=><div className="vop-admin-card" key={i} style={{marginBottom:10}}><div className="vop-admin-heading" style={{marginBottom:8}}><strong>Page {i+1}</strong><button className="vop-admin-btn danger" onClick={()=>removePage(i)}><Trash2 size={13}/>Remove</button></div><div className="vop-admin-formgrid"><label><span className="vop-admin-label">Page title</span><input className="vop-admin-input" value={page.title} onChange={e=>updatePage(i,{title:e.target.value})}/></label><label><span className="vop-admin-label">Scripture reference</span><input className="vop-admin-input" value={page.scriptureQuote?.reference||''} onChange={e=>updatePage(i,{scriptureQuote:{text:page.scriptureQuote?.text||'',reference:e.target.value}})}/></label><label className="vop-admin-full"><span className="vop-admin-label">Content</span><textarea className="vop-admin-textarea" value={page.content} onChange={e=>updatePage(i,{content:e.target.value})}/></label><label className="vop-admin-full"><span className="vop-admin-label">Scripture text</span><textarea className="vop-admin-textarea" value={page.scriptureQuote?.text||''} onChange={e=>updatePage(i,{scriptureQuote:{reference:page.scriptureQuote?.reference||'',text:e.target.value}})}/></label><label className="vop-admin-full"><span className="vop-admin-label">Key takeaway</span><textarea className="vop-admin-textarea" value={page.keyTakeaway||''} onChange={e=>updatePage(i,{keyTakeaway:e.target.value})}/></label><label className="vop-admin-full"><span className="vop-admin-label">Image URL / path</span><input className="vop-admin-input" value={page.imageUrl||''} onChange={e=>updatePage(i,{imageUrl:e.target.value})}/></label></div></div>)}{!(lessonEditor.lesson.contentPages||[]).length&&<div className="vop-admin-empty">No lesson pages yet. Add a page above.</div>}</div>
    <div className="vop-admin-section"><div className="vop-admin-section-title">Test questions (JSON)</div><textarea className="vop-admin-textarea" value={JSON.stringify(lessonEditor.lesson.questions||[],null,2)} onChange={e=>{try{const q=JSON.parse(e.target.value);if(Array.isArray(q))setLessonEditor({...lessonEditor,lesson:{...lessonEditor.lesson,questions:q}})}catch{}}}/></div>
    <div className="vop-admin-actions" style={{marginTop:16}}><button className="vop-admin-btn primary" disabled={saving} onClick={()=>void saveLessonEditor()}><Save size={14}/>Save Lesson</button><button className="vop-admin-btn" onClick={()=>setLessonEditor(null)}>Cancel</button></div></div></div></div>}
  </div>;
};
