type LegalPolicyPageProps={kind:'privacy'|'terms'};

const updated='5 October 2026';

export function LegalPolicyPage({kind}:LegalPolicyPageProps){
  const privacy=kind==='privacy';
  return <main className="vop-page-shell" style={{maxWidth:980,margin:'0 auto',padding:'28px 18px 56px'}}>
    <header className="vop-page-head">
      <div className="vop-heading"><div><p className="vop-kicker">Voice of Prophecy</p><h1>{privacy?'Privacy Policy':'Terms of Service'}</h1><p>Effective and last updated: {updated}</p></div></div>
      <a className="vop-secondary" href="/">Return to VOP</a>
    </header>
    {privacy?<div style={{display:'grid',gap:16}}>
      <section className="vop-card"><h2>What VOP collects</h2><p>VOP processes account identity and contact details, organization or church membership, study progress, assessment attempts, certificates, mentoring and support activity, notification preferences, engagement activity, portfolio evidence, prayer requests, invitations, and payment records when those features are used.</p></section>
      <section className="vop-card"><h2>Why the data is used</h2><p>Data is used to provide authentication, course delivery, progress and assessment integrity, mentoring and learner support, certificate issuance and verification, organization administration, subscriptions and payments, security, fraud prevention, service notifications, accessibility preferences, and statutory or operational record keeping.</p></section>
      <section className="vop-card"><h2>Access and tenant isolation</h2><p>Access is limited by account role, organization and hierarchy scope. Private learner, mentoring, assessment and financial records are not intended for public access. Public verification endpoints expose only the minimum information required for the relevant verification function.</p></section>
      <section className="vop-card"><h2>Retention and deletion</h2><p>Account deletion uses a 30-day recovery period. During that period the request can be cancelled. After the grace period, profile data, personal settings, study progress, personal assessment attempts, notifications, engagement state, portfolio records, prayer requests, invitations and learner-owned support records are deleted or de-identified.</p><p>Official certificate records are retained for credential integrity. Financial transactions, receipts, refunds and security/privileged audit records are retained for seven years for accounting, reconciliation, fraud prevention and audit purposes, with account identifiers and contact fields pseudonymized where practical. A minimal non-identifying deletion tombstone may be kept to prove that the lifecycle completed.</p></section>
      <section className="vop-card"><h2>Your controls</h2><p>Signed-in users can export their VOP account data, request deletion, review deletion status and cancel a pending request before the grace period ends from Personal Settings. Organization owners, Super Admins and mentors with active learner assignments must first transfer their operational responsibilities so deletion cannot orphan a tenant or learner.</p></section>
      <section className="vop-card"><h2>Security and service providers</h2><p>VOP uses Firebase and deployment, communication and payment providers to operate the service. Provider credentials remain server-side. Payment callbacks are not treated as financial proof without independent provider verification. VOP does not intentionally include passwords, private keys, payment secrets or official assessment answer keys in user exports.</p></section>
      <section className="vop-card"><h2>Questions and requests</h2><p>Use the in-app Support channel or the contact information published by your VOP organization for privacy questions, access requests or concerns about a deletion/export request.</p></section>
    </div>:<div style={{display:'grid',gap:16}}>
      <section className="vop-card"><h2>Using the service</h2><p>VOP provides digital Bible-study, learning, mentoring, engagement, certificate, organization and related ministry services. You must use the service lawfully and provide accurate information when the service requires it.</p></section>
      <section className="vop-card"><h2>Accounts and security</h2><p>You are responsible for safeguarding your sign-in methods and for activity performed through your account. Do not share credentials, attempt to bypass role or tenant boundaries, manipulate assessment outcomes, forge certificates, alter payment state, or interfere with another user’s data.</p></section>
      <section className="vop-card"><h2>Learning, assessments and certificates</h2><p>Assessment grading, completion and certificate eligibility are determined by the authoritative server-side rules configured for the applicable course, programme or organization. A certificate may be withheld, revoked or replaced when the underlying eligibility, integrity or administrative requirements are not satisfied.</p></section>
      <section className="vop-card"><h2>Organizations and administrators</h2><p>Organizations are responsible for the content, staff assignments and configuration they control within their authorized tenant scope. Administrative access does not authorize access to another organization or hierarchy outside the administrator’s assigned scope.</p></section>
      <section className="vop-card"><h2>Payments</h2><p>Paid services are activated only after the configured payment provider independently confirms a successful transaction. Pending or failed transactions do not create an entitlement. Refund eligibility depends on the applicable programme, event, organization and payment-provider rules.</p></section>
      <section className="vop-card"><h2>Availability and acceptable use</h2><p>VOP may apply rate limits, abuse controls, maintenance windows and security restrictions to protect the platform. Do not probe for unauthorized data, abuse invitations or messaging, submit malicious content, or use automated traffic in a way that degrades service for others.</p></section>
      <section className="vop-card"><h2>Account termination and retained records</h2><p>You may request account deletion from Personal Settings subject to the privacy retention policy. VOP may suspend or restrict accounts for security, legal, integrity or serious policy violations. Required financial, audit and issued-credential records can remain after account deletion as described in the Privacy Policy.</p></section>
      <section className="vop-card"><h2>Changes and support</h2><p>Material changes to these terms should be published with an updated effective date. Questions can be sent through the in-app Support channel or the contact information published by your VOP organization.</p></section>
    </div>}
  </main>;
}
