import React, { u{t('common.pluralSuffix', 's')}eEffect, u{t('common.pluralSuffix', 's')}eState } from 'react';
import { Building2, Check, Edit3, Plu{t('common.pluralSuffix', 's')}, {t('common.refre{t('common.pluralSuffix', 's')}h', 'Refre{t('common.pluralSuffix', 's')}h')}Cw, Shield, U{t('common.pluralSuffix', 's')}er{t('common.pluralSuffix', 's')}, BarChart3, BookOpen, Award } from 'lucide-react';
import { auth } from '../lib/fireba{t('common.pluralSuffix', 's')}e';
import { u{t('common.pluralSuffix', 's')}eLocalization } from '../{t('common.pluralSuffix', 's')}ervice{t('common.pluralSuffix', 's')}/i18n';

type Organization = {
  id:{t('common.pluralSuffix', 's')}tring; name:{t('common.pluralSuffix', 's')}tring; {t('common.pluralSuffix', 's')}lug:{t('common.pluralSuffix', 's')}tring; {t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')}:{t('common.pluralSuffix', 's')}tring; ownerUid:{t('common.pluralSuffix', 's')}tring; plan:{t('common.pluralSuffix', 's')}tring;
  quota{t('common.pluralSuffix', 's')}:Record<{t('common.pluralSuffix', 's')}tring,unknown>; memberCount:number; createdAt?:{t('common.pluralSuffix', 's')}tring;
};
type Member = { id:{t('common.pluralSuffix', 's')}tring; uid:{t('common.pluralSuffix', 's')}tring; role:{t('common.pluralSuffix', 's')}tring; active:boolean; joinedAt?:{t('common.pluralSuffix', 's')}tring };
type {t('organizations.plan', 'Plan')} = { id:{t('common.pluralSuffix', 's')}tring; name:{t('common.pluralSuffix', 's')}tring; de{t('common.pluralSuffix', 's')}cription?:{t('common.pluralSuffix', 's')}tring; active:boolean; quota{t('common.pluralSuffix', 's')}:Record<{t('common.pluralSuffix', 's')}tring,unknown>; feature{t('common.pluralSuffix', 's')}:Record<{t('common.pluralSuffix', 's')}tring,boolean> };
type U{t('common.pluralSuffix', 's')}age = { member{t('common.pluralSuffix', 's')}:number; guide{t('common.pluralSuffix', 's')}:number; quizze{t('common.pluralSuffix', 's')}:number; announcement{t('common.pluralSuffix', 's')}:number; radio:number; book{t('common.pluralSuffix', 's')}:number; playli{t('common.pluralSuffix', 's')}t{t('common.pluralSuffix', 's')}?:number }; type Analytic{t('common.pluralSuffix', 's')} = { member{t('common.pluralSuffix', 's')}:number; roleCount{t('common.pluralSuffix', 's')}:Record<{t('common.pluralSuffix', 's')}tring,number>; content:Record<{t('common.pluralSuffix', 's')}tring,number>; recentActivity:Array<Record<{t('common.pluralSuffix', 's')}tring,unknown>> };

a{t('common.pluralSuffix', 's')}ync function api(action:{t('common.pluralSuffix', 's')}tring, payload:Record<{t('common.pluralSuffix', 's')}tring,unknown>={}) {
  if (!auth?.currentU{t('common.pluralSuffix', 's')}er) throw new Error('{t('authentication.{t('common.pluralSuffix', 's')}e{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}ionExpired', 'Your {t('common.pluralSuffix', 's')}e{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}ion ha{t('common.pluralSuffix', 's')} expired. Sign in again.')}');
  con{t('common.pluralSuffix', 's')}t token=await auth.currentU{t('common.pluralSuffix', 's')}er.getIdToken();
  con{t('common.pluralSuffix', 's')}t re{t('common.pluralSuffix', 's')}pon{t('common.pluralSuffix', 's')}e=await fetch('/api/admin/organization{t('common.pluralSuffix', 's')}',{method:'POST',header{t('common.pluralSuffix', 's')}:{'Content-Type':'application/j{t('common.pluralSuffix', 's')}on',Authorization:'Bearer '+token},body:JSON.{t('common.pluralSuffix', 's')}tringify({action,...payload})});
  con{t('common.pluralSuffix', 's')}t body=await re{t('common.pluralSuffix', 's')}pon{t('common.pluralSuffix', 's')}e.j{t('common.pluralSuffix', 's')}on().catch(()=>({})) a{t('common.pluralSuffix', 's')} {error?:{t('common.pluralSuffix', 's')}tring;item{t('common.pluralSuffix', 's')}?:unknown[];item?:Organization;u{t('common.pluralSuffix', 's')}age?:U{t('common.pluralSuffix', 's')}age;analytic{t('common.pluralSuffix', 's')}?:Analytic{t('common.pluralSuffix', 's')}};
  if(!re{t('common.pluralSuffix', 's')}pon{t('common.pluralSuffix', 's')}e.ok) throw new Error(body.error || '{t('error{t('common.pluralSuffix', 's')}.organizationReque{t('common.pluralSuffix', 's')}tFailed', 'Organization reque{t('common.pluralSuffix', 's')}t failed.')}');
  return body;
}

export default function OrganizationManagement({i{t('common.pluralSuffix', 's')}Super{t('common.admin', 'Admin')}}:{i{t('common.pluralSuffix', 's')}Super{t('common.admin', 'Admin')}:boolean}) {
  con{t('common.pluralSuffix', 's')}t { t } = u{t('common.pluralSuffix', 's')}eLocalization();
  con{t('common.pluralSuffix', 's')}t [item{t('common.pluralSuffix', 's')},{t('common.pluralSuffix', 's')}etItem{t('common.pluralSuffix', 's')}]=u{t('common.pluralSuffix', 's')}eState<Organization[]>([]);
  con{t('common.pluralSuffix', 's')}t [plan{t('common.pluralSuffix', 's')},{t('common.pluralSuffix', 's')}et{t('organizations.plan', 'Plan')}{t('common.pluralSuffix', 's')}]=u{t('common.pluralSuffix', 's')}eState<{t('organizations.plan', 'Plan')}[]>([]);
  con{t('common.pluralSuffix', 's')}t [{t('common.pluralSuffix', 's')}elected,{t('common.pluralSuffix', 's')}etSelected]=u{t('common.pluralSuffix', 's')}eState<Organization|null>(null);
  con{t('common.pluralSuffix', 's')}t [member{t('common.pluralSuffix', 's')},{t('common.pluralSuffix', 's')}etMember{t('common.pluralSuffix', 's')}]=u{t('common.pluralSuffix', 's')}eState<Member[]>([]);
  con{t('common.pluralSuffix', 's')}t [u{t('common.pluralSuffix', 's')}age,{t('common.pluralSuffix', 's')}etU{t('common.pluralSuffix', 's')}age]=u{t('common.pluralSuffix', 's')}eState<U{t('common.pluralSuffix', 's')}age|null>(null); con{t('common.pluralSuffix', 's')}t [analytic{t('common.pluralSuffix', 's')},{t('common.pluralSuffix', 's')}etAnalytic{t('common.pluralSuffix', 's')}]=u{t('common.pluralSuffix', 's')}eState<Analytic{t('common.pluralSuffix', 's')}|null>(null);
  con{t('common.pluralSuffix', 's')}t [name,{t('common.pluralSuffix', 's')}et{t('common.name', 'Name')}]=u{t('common.pluralSuffix', 's')}eState('');
  con{t('common.pluralSuffix', 's')}t [organizationId,{t('common.pluralSuffix', 's')}etOrganizationId]=u{t('common.pluralSuffix', 's')}eState('');
  con{t('common.pluralSuffix', 's')}t [plan,{t('common.pluralSuffix', 's')}et{t('organizations.plan', 'Plan')}]=u{t('common.pluralSuffix', 's')}eState('');
  con{t('common.pluralSuffix', 's')}t [{t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')},{t('common.pluralSuffix', 's')}et{t('common.{t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')}', 'Statu{t('common.pluralSuffix', 's')}')}]=u{t('common.pluralSuffix', 's')}eState('active'); con{t('common.pluralSuffix', 's')}t [quota{t('common.pluralSuffix', 's')},{t('common.pluralSuffix', 's')}etQuota{t('common.pluralSuffix', 's')}]=u{t('common.pluralSuffix', 's')}eState('{}'); con{t('common.pluralSuffix', 's')}t [branding,{t('common.pluralSuffix', 's')}etBranding]=u{t('common.pluralSuffix', 's')}eState('{}'); con{t('common.pluralSuffix', 's')}t [tenantSetting{t('common.pluralSuffix', 's')},{t('common.pluralSuffix', 's')}etTenantSetting{t('common.pluralSuffix', 's')}]=u{t('common.pluralSuffix', 's')}eState('{}');
  con{t('common.pluralSuffix', 's')}t [memberUid,{t('common.pluralSuffix', 's')}etMemberUid]=u{t('common.pluralSuffix', 's')}eState(''); con{t('common.pluralSuffix', 's')}t [invite{t('common.email', 'Email')},{t('common.pluralSuffix', 's')}etInvite{t('common.email', 'Email')}]=u{t('common.pluralSuffix', 's')}eState(''); con{t('common.pluralSuffix', 's')}t [invite{t('common.role', 'Role')},{t('common.pluralSuffix', 's')}etInvite{t('common.role', 'Role')}]=u{t('common.pluralSuffix', 's')}eState('learner'); con{t('common.pluralSuffix', 's')}t [inviteUrl,{t('common.pluralSuffix', 's')}etInviteUrl]=u{t('common.pluralSuffix', 's')}eState('');
  con{t('common.pluralSuffix', 's')}t [member{t('common.role', 'Role')},{t('common.pluralSuffix', 's')}etMember{t('common.role', 'Role')}]=u{t('common.pluralSuffix', 's')}eState('learner');
  con{t('common.pluralSuffix', 's')}t [{t('common.pluralSuffix', 's')}aving,{t('common.pluralSuffix', 's')}etSaving]=u{t('common.pluralSuffix', 's')}eState(fal{t('common.pluralSuffix', 's')}e);
  con{t('common.pluralSuffix', 's')}t [loading,{t('common.pluralSuffix', 's')}etLoading]=u{t('common.pluralSuffix', 's')}eState(true);
  con{t('common.pluralSuffix', 's')}t [me{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}age,{t('common.pluralSuffix', 's')}etMe{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}age]=u{t('common.pluralSuffix', 's')}eState(''); con{t('common.pluralSuffix', 's')}t [audit,{t('common.pluralSuffix', 's')}etAudit]=u{t('common.pluralSuffix', 's')}eState<Array<Record<{t('common.pluralSuffix', 's')}tring,unknown>>>([]);
  con{t('common.pluralSuffix', 's')}t [invite{t('common.pluralSuffix', 's')},{t('common.pluralSuffix', 's')}etInvite{t('common.pluralSuffix', 's')}]=u{t('common.pluralSuffix', 's')}eState<Array<Record<{t('common.pluralSuffix', 's')}tring,unknown>>>([]);
  con{t('common.pluralSuffix', 's')}t [error,{t('common.pluralSuffix', 's')}etError]=u{t('common.pluralSuffix', 's')}eState('');

  con{t('common.pluralSuffix', 's')}t load=a{t('common.pluralSuffix', 's')}ync()=>{
    {t('common.pluralSuffix', 's')}etLoading(true);{t('common.pluralSuffix', 's')}etError('');
    try {
      con{t('common.pluralSuffix', 's')}t body=await api('li{t('common.pluralSuffix', 's')}t');
      con{t('common.pluralSuffix', 's')}t next=(body.item{t('common.pluralSuffix', 's')}||[]) a{t('common.pluralSuffix', 's')} Organization[];
      {t('common.pluralSuffix', 's')}etItem{t('common.pluralSuffix', 's')}(next);
      if({t('common.pluralSuffix', 's')}elected) {
        con{t('common.pluralSuffix', 's')}t fre{t('common.pluralSuffix', 's')}h=next.find(item=>item.id==={t('common.pluralSuffix', 's')}elected.id)||{t('common.pluralSuffix', 's')}elected;
        {t('common.pluralSuffix', 's')}etSelected(fre{t('common.pluralSuffix', 's')}h);
        await loadDetail{t('common.pluralSuffix', 's')}(fre{t('common.pluralSuffix', 's')}h.id);
      }
    } catch(e){{t('common.pluralSuffix', 's')}etError(e in{t('common.pluralSuffix', 's')}tanceof Error?e.me{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}age:'{t('organization{t('common.pluralSuffix', 's')}.loadFailed', 'Could not load organization{t('common.pluralSuffix', 's')}.')}');}
    finally{{t('common.pluralSuffix', 's')}etLoading(fal{t('common.pluralSuffix', 's')}e);}
  };
  con{t('common.pluralSuffix', 's')}t loadDetail{t('common.pluralSuffix', 's')}=a{t('common.pluralSuffix', 's')}ync(id:{t('common.pluralSuffix', 's')}tring)=>{
    try {
      con{t('common.pluralSuffix', 's')}t [m,u,a,an,iv]=await Promi{t('common.pluralSuffix', 's')}e.all([api('li{t('common.pluralSuffix', 's')}tMember{t('common.pluralSuffix', 's')}',{organizationId:id}),api('getU{t('common.pluralSuffix', 's')}age',{organizationId:id}),api('li{t('common.pluralSuffix', 's')}tAudit',{organizationId:id}),api('getAnalytic{t('common.pluralSuffix', 's')}',{organizationId:id}),api('li{t('common.pluralSuffix', 's')}tInvite{t('common.pluralSuffix', 's')}',{organizationId:id})]);
      {t('common.pluralSuffix', 's')}etMember{t('common.pluralSuffix', 's')}((m.item{t('common.pluralSuffix', 's')}||[]) a{t('common.pluralSuffix', 's')} Member[]);{t('common.pluralSuffix', 's')}etU{t('common.pluralSuffix', 's')}age(u.u{t('common.pluralSuffix', 's')}age||null);{t('common.pluralSuffix', 's')}etAudit((a.item{t('common.pluralSuffix', 's')}||[]) a{t('common.pluralSuffix', 's')} Array<Record<{t('common.pluralSuffix', 's')}tring,unknown>>);{t('common.pluralSuffix', 's')}etAnalytic{t('common.pluralSuffix', 's')}((an.analytic{t('common.pluralSuffix', 's')}||null) a{t('common.pluralSuffix', 's')} Analytic{t('common.pluralSuffix', 's')}|null);{t('common.pluralSuffix', 's')}etInvite{t('common.pluralSuffix', 's')}((iv.item{t('common.pluralSuffix', 's')}||[]) a{t('common.pluralSuffix', 's')} Array<Record<{t('common.pluralSuffix', 's')}tring,unknown>>);
    } catch(e){{t('common.pluralSuffix', 's')}etError(e in{t('common.pluralSuffix', 's')}tanceof Error?e.me{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}age:'Could not load organization detail{t('common.pluralSuffix', 's')}.');}
  };
  u{t('common.pluralSuffix', 's')}eEffect(()=>{void load(); if(i{t('common.pluralSuffix', 's')}Super{t('common.admin', 'Admin')}) void api('li{t('common.pluralSuffix', 's')}t{t('organizations.plan', 'Plan')}{t('common.pluralSuffix', 's')}').then(body=>{t('common.pluralSuffix', 's')}et{t('organizations.plan', 'Plan')}{t('common.pluralSuffix', 's')}((body.item{t('common.pluralSuffix', 's')}||[]) a{t('common.pluralSuffix', 's')} {t('organizations.plan', 'Plan')}[])).catch(()=>undefined);},[]);

  con{t('common.pluralSuffix', 's')}t create=a{t('common.pluralSuffix', 's')}ync()=>{
    if(!name.trim()) return;
    {t('common.pluralSuffix', 's')}etSaving(true);{t('common.pluralSuffix', 's')}etError('');
    try {
      con{t('common.pluralSuffix', 's')}t body=await api('create',{name:name.trim(),id:organizationId.trim()||undefined});
      {t('common.pluralSuffix', 's')}et{t('common.name', 'Name')}('');{t('common.pluralSuffix', 's')}etOrganizationId('');{t('common.pluralSuffix', 's')}etMe{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}age('{t('organization{t('common.pluralSuffix', 's')}.created', 'Organization created.')}');
      await load();
      con{t('common.pluralSuffix', 's')}t created=(body.item||null) a{t('common.pluralSuffix', 's')} Organization|null;
      if(created){{t('common.pluralSuffix', 's')}etSelected(created);await loadDetail{t('common.pluralSuffix', 's')}(created.id);}
    }catch(e){{t('common.pluralSuffix', 's')}etError(e in{t('common.pluralSuffix', 's')}tanceof Error?e.me{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}age:'{t('organization{t('common.pluralSuffix', 's')}.createFailed', 'Could not create organization.')}');}
    finally{{t('common.pluralSuffix', 's')}etSaving(fal{t('common.pluralSuffix', 's')}e);}
  };
  con{t('common.pluralSuffix', 's')}t {t('common.pluralSuffix', 's')}ave=a{t('common.pluralSuffix', 's')}ync()=>{
    if(!{t('common.pluralSuffix', 's')}elected) return;
    {t('common.pluralSuffix', 's')}etSaving(true);{t('common.pluralSuffix', 's')}etError('');
    try{
      let par{t('common.pluralSuffix', 's')}edQuota{t('common.pluralSuffix', 's')}:Record<{t('common.pluralSuffix', 's')}tring,unknown>={}; let par{t('common.pluralSuffix', 's')}edBranding:Record<{t('common.pluralSuffix', 's')}tring,unknown>={}; let par{t('common.pluralSuffix', 's')}edSetting{t('common.pluralSuffix', 's')}:Record<{t('common.pluralSuffix', 's')}tring,unknown>={}; try { par{t('common.pluralSuffix', 's')}edQuota{t('common.pluralSuffix', 's')}=JSON.par{t('common.pluralSuffix', 's')}e(quota{t('common.pluralSuffix', 's')}||'{}'); par{t('common.pluralSuffix', 's')}edBranding=JSON.par{t('common.pluralSuffix', 's')}e(branding||'{}'); par{t('common.pluralSuffix', 's')}edSetting{t('common.pluralSuffix', 's')}=JSON.par{t('common.pluralSuffix', 's')}e(tenantSetting{t('common.pluralSuffix', 's')}||'{}'); if([par{t('common.pluralSuffix', 's')}edQuota{t('common.pluralSuffix', 's')},par{t('common.pluralSuffix', 's')}edBranding,par{t('common.pluralSuffix', 's')}edSetting{t('common.pluralSuffix', 's')}].{t('common.pluralSuffix', 's')}ome(v=>!v || Array.i{t('common.pluralSuffix', 's')}Array(v) || typeof v!=='object')) throw new Error(); } catch { throw new Error('Quota{t('common.pluralSuffix', 's')}, branding and tenant {t('common.pluralSuffix', 's')}etting{t('common.pluralSuffix', 's')} mu{t('common.pluralSuffix', 's')}t each be valid JSON object{t('common.pluralSuffix', 's')}.'); } await api('update',{organizationId:{t('common.pluralSuffix', 's')}elected.id,data:{name:name.trim()||{t('common.pluralSuffix', 's')}elected.name,plan,{t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')},quota{t('common.pluralSuffix', 's')}:par{t('common.pluralSuffix', 's')}edQuota{t('common.pluralSuffix', 's')},branding:par{t('common.pluralSuffix', 's')}edBranding,{t('common.pluralSuffix', 's')}etting{t('common.pluralSuffix', 's')}:par{t('common.pluralSuffix', 's')}edSetting{t('common.pluralSuffix', 's')}}});
      if({t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')}!=={t('common.pluralSuffix', 's')}elected.{t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')}) await api('{t('common.pluralSuffix', 's')}et{t('common.{t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')}', 'Statu{t('common.pluralSuffix', 's')}')}',{organizationId:{t('common.pluralSuffix', 's')}elected.id,{t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')}});
      {t('common.pluralSuffix', 's')}etMe{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}age('{t('organization{t('common.pluralSuffix', 's')}.{t('common.pluralSuffix', 's')}etting{t('common.pluralSuffix', 's')}Saved', 'Organization {t('common.pluralSuffix', 's')}etting{t('common.pluralSuffix', 's')} {t('common.pluralSuffix', 's')}aved.')}');await load();
    }catch(e){{t('common.pluralSuffix', 's')}etError(e in{t('common.pluralSuffix', 's')}tanceof Error?e.me{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}age:'{t('organization{t('common.pluralSuffix', 's')}.{t('common.pluralSuffix', 's')}aveFailed', 'Could not {t('common.pluralSuffix', 's')}ave organization.')}');}
    finally{{t('common.pluralSuffix', 's')}etSaving(fal{t('common.pluralSuffix', 's')}e);}
  };
  con{t('common.pluralSuffix', 's')}t invite=a{t('common.pluralSuffix', 's')}ync()=>{if(!{t('common.pluralSuffix', 's')}elected||!invite{t('common.email', 'Email')}.trim())return;{t('common.pluralSuffix', 's')}etSaving(true);{t('common.pluralSuffix', 's')}etError('');try{con{t('common.pluralSuffix', 's')}t body=await api('{t('common.pluralSuffix', 's')}endInvite',{organizationId:{t('common.pluralSuffix', 's')}elected.id,email:invite{t('common.email', 'Email')}.trim(),role:invite{t('common.role', 'Role')}});{t('common.pluralSuffix', 's')}etInviteUrl(String((body.item a{t('common.pluralSuffix', 's')} {inviteUrl?:{t('common.pluralSuffix', 's')}tring}|undefined)?.inviteUrl||''));{t('common.pluralSuffix', 's')}etInvite{t('common.email', 'Email')}('');{t('common.pluralSuffix', 's')}etMe{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}age('{t('organization{t('common.pluralSuffix', 's')}.invitationCreated', 'Invitation created.')}');}catch(e){{t('common.pluralSuffix', 's')}etError(e in{t('common.pluralSuffix', 's')}tanceof Error?e.me{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}age:'{t('organization{t('common.pluralSuffix', 's')}.invitationFailed', 'Could not create invitation.')}');}finally{{t('common.pluralSuffix', 's')}etSaving(fal{t('common.pluralSuffix', 's')}e);}};
  con{t('common.pluralSuffix', 's')}t revokeInvite=a{t('common.pluralSuffix', 's')}ync(token:{t('common.pluralSuffix', 's')}tring)=>{
    {t('common.pluralSuffix', 's')}etSaving(true);{t('common.pluralSuffix', 's')}etError('');
    try{await api('revokeInvite',{organizationId:{t('common.pluralSuffix', 's')}elected?.id,token});{t('common.pluralSuffix', 's')}etMe{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}age('{t('organization{t('common.pluralSuffix', 's')}.invitation{t('common.revoke', 'Revoke')}d', 'Invitation revoked.')}');if({t('common.pluralSuffix', 's')}elected) await loadDetail{t('common.pluralSuffix', 's')}({t('common.pluralSuffix', 's')}elected.id);}
    catch(e){{t('common.pluralSuffix', 's')}etError(e in{t('common.pluralSuffix', 's')}tanceof Error?e.me{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}age:'{t('organization{t('common.pluralSuffix', 's')}.invitation{t('common.revoke', 'Revoke')}Failed', 'Could not revoke invitation.')}');}finally{{t('common.pluralSuffix', 's')}etSaving(fal{t('common.pluralSuffix', 's')}e);}
  };
  con{t('common.pluralSuffix', 's')}t re{t('common.pluralSuffix', 's')}endInvite=a{t('common.pluralSuffix', 's')}ync(token:{t('common.pluralSuffix', 's')}tring)=>{
    {t('common.pluralSuffix', 's')}etSaving(true);{t('common.pluralSuffix', 's')}etError('');
    try{con{t('common.pluralSuffix', 's')}t body=await api('re{t('common.pluralSuffix', 's')}endInvite',{organizationId:{t('common.pluralSuffix', 's')}elected?.id,token});{t('common.pluralSuffix', 's')}etInviteUrl(String((body.item a{t('common.pluralSuffix', 's')} {inviteUrl?:{t('common.pluralSuffix', 's')}tring}|undefined)?.inviteUrl||''));{t('common.pluralSuffix', 's')}etMe{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}age('{t('organization{t('common.pluralSuffix', 's')}.invitationRe{t('common.pluralSuffix', 's')}ent', 'Invitation re{t('common.pluralSuffix', 's')}ent.')}');if({t('common.pluralSuffix', 's')}elected) await loadDetail{t('common.pluralSuffix', 's')}({t('common.pluralSuffix', 's')}elected.id);}
    catch(e){{t('common.pluralSuffix', 's')}etError(e in{t('common.pluralSuffix', 's')}tanceof Error?e.me{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}age:'{t('organization{t('common.pluralSuffix', 's')}.invitation{t('common.re{t('common.pluralSuffix', 's')}end', 'Re{t('common.pluralSuffix', 's')}end')}Failed', 'Could not re{t('common.pluralSuffix', 's')}end invitation.')}');}finally{{t('common.pluralSuffix', 's')}etSaving(fal{t('common.pluralSuffix', 's')}e);}
  };

  con{t('common.pluralSuffix', 's')}t addMember=a{t('common.pluralSuffix', 's')}ync()=>{
    if(!{t('common.pluralSuffix', 's')}elected||!memberUid.trim()) return;
    {t('common.pluralSuffix', 's')}etSaving(true);{t('common.pluralSuffix', 's')}etError('');
    try{await api('{t('common.pluralSuffix', 's')}etMember',{organizationId:{t('common.pluralSuffix', 's')}elected.id,uid:memberUid.trim(),role:member{t('common.role', 'Role')},active:true});{t('common.pluralSuffix', 's')}etMemberUid('');{t('common.pluralSuffix', 's')}etMe{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}age('{t('organization{t('common.pluralSuffix', 's')}.member{t('common.pluralSuffix', 's')}hipSaved', 'Organization member{t('common.pluralSuffix', 's')}hip {t('common.pluralSuffix', 's')}aved.')}');await loadDetail{t('common.pluralSuffix', 's')}({t('common.pluralSuffix', 's')}elected.id);await load();}
    catch(e){{t('common.pluralSuffix', 's')}etError(e in{t('common.pluralSuffix', 's')}tanceof Error?e.me{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}age:'{t('organization{t('common.pluralSuffix', 's')}.member{t('common.pluralSuffix', 's')}hipFailed', 'Could not {t('common.pluralSuffix', 's')}ave member{t('common.pluralSuffix', 's')}hip.')}');}
    finally{{t('common.pluralSuffix', 's')}etSaving(fal{t('common.pluralSuffix', 's')}e);}
  };

  return <div>
    {{t('common.pluralSuffix', 's')}elected && (
      <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-card" {t('common.pluralSuffix', 's')}tyle={{marginTop:16}}>
        <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-{t('common.pluralSuffix', 's')}ection-title"><div><h2>{t('organization{t('common.pluralSuffix', 's')}.invitationLifecycle', 'Invitation lifecycle')}</h2><p>{t('organization{t('common.pluralSuffix', 's')}.invitationLifecycleHelp', 'Pending invitation{t('common.pluralSuffix', 's')} expire after {t('common.pluralSuffix', 's')}even day{t('common.pluralSuffix', 's')} and can be re{t('common.pluralSuffix', 's')}ent or revoked.')}</p></div></div>
        {invite{t('common.pluralSuffix', 's')}.length===0 ? <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-empty">{t('organization{t('common.pluralSuffix', 's')}.noInvitation{t('common.pluralSuffix', 's')}', 'No invitation{t('common.pluralSuffix', 's')} have been created.')}</div> : <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-reference-table-wrap"><table cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-reference-table"><thead><tr><th>{t('common.email', 'Email')}</th><th>{t('common.role', 'Role')}</th><th>{t('common.{t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')}', 'Statu{t('common.pluralSuffix', 's')}')}</th><th>{t('common.expire{t('common.pluralSuffix', 's')}', 'Expire{t('common.pluralSuffix', 's')}')}</th><th>{t('common.action{t('common.pluralSuffix', 's')}', '{t('common.action', 'Action')}{t('common.pluralSuffix', 's')}')}</th></tr></thead><tbody>{invite{t('common.pluralSuffix', 's')}.map(invite=>{con{t('common.pluralSuffix', 's')}t token=String(invite.token||invite.id||'');con{t('common.pluralSuffix', 's')}t {t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')}=String(invite.{t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')}||'pending');return <tr key={token}><td>{String(invite.email||'')}</td><td>{String(invite.role||'learner')}</td><td>{{t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')}}</td><td>{String(invite.expire{t('common.pluralSuffix', 's')}At||'')}</td><td><div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-reference-action-cell">{({t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')}==='pending'||{t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')}==='expired')&&<button cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-action{t('common.pluralSuffix', 's')}" type="button" onClick={()=>void re{t('common.pluralSuffix', 's')}endInvite(token)} title="{t('common.re{t('common.pluralSuffix', 's')}end', 'Re{t('common.pluralSuffix', 's')}end')}">↻</button>}{{t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')}==='pending'&&<button cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-action{t('common.pluralSuffix', 's')}" type="button" onClick={()=>void revokeInvite(token)} title="{t('common.revoke', 'Revoke')}">×</button>}</div></td></tr>;})}</tbody></table></div>}
      </div>
    )}

    <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-page-header">
      <div><div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-breadcrumb"><Building2 {t('common.pluralSuffix', 's')}ize={15}/> {t('organization{t('common.pluralSuffix', 's')}.breadcrumb', 'Platform / {t('organization{t('common.pluralSuffix', 's')}.title', 'Organization{t('common.pluralSuffix', 's')}')}')}</div><h1>{t('organization{t('common.pluralSuffix', 's')}.title', 'Organization{t('common.pluralSuffix', 's')}')}</h1><p>{t('organization{t('common.pluralSuffix', 's')}.de{t('common.pluralSuffix', 's')}cription', 'Manage tenant work{t('common.pluralSuffix', 's')}pace{t('common.pluralSuffix', 's')}, member{t('common.pluralSuffix', 's')}hip, plan{t('common.pluralSuffix', 's')} and u{t('common.pluralSuffix', 's')}age without {t('common.pluralSuffix', 's')}haring operational data between organization{t('common.pluralSuffix', 's')}.')}</p></div>
      <button cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-{t('common.pluralSuffix', 's')}econdary" type="button" onClick={()=>void load()}><{t('common.refre{t('common.pluralSuffix', 's')}h', 'Refre{t('common.pluralSuffix', 's')}h')}Cw {t('common.pluralSuffix', 's')}ize={16}/>{t('common.refre{t('common.pluralSuffix', 's')}h', 'Refre{t('common.pluralSuffix', 's')}h')}</button>
    </div>
    {me{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}age&&<div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-toa{t('common.pluralSuffix', 's')}t"><Check {t('common.pluralSuffix', 's')}ize={16}/>{me{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}age}</div>}
    {error&&<div role="alert" {t('common.pluralSuffix', 's')}tyle={{background:'#fff1f1',border:'1px {t('common.pluralSuffix', 's')}olid #ffcaca',color:'#b42318',padding:12,borderRadiu{t('common.pluralSuffix', 's')}:11,marginBottom:14}}>{error}</div>}
    {i{t('common.pluralSuffix', 's')}Super{t('common.admin', 'Admin')}&&<div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-card vop-form-card" {t('common.pluralSuffix', 's')}tyle={{marginBottom:16}}>
      <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-{t('common.pluralSuffix', 's')}ection-title"><div><h2>{t('organization{t('common.pluralSuffix', 's')}.createTitle', 'Create organization')}</h2><p>{t('organization{t('common.pluralSuffix', 's')}.createHelp', 'Create an i{t('common.pluralSuffix', 's')}olated work{t('common.pluralSuffix', 's')}pace for an in{t('common.pluralSuffix', 's')}titution or mini{t('common.pluralSuffix', 's')}try.')}</p></div><Shield {t('common.pluralSuffix', 's')}ize={22}/></div>
      <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-form-grid">
        <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-field"><label>{t('organization{t('common.pluralSuffix', 's')}.nameRequired', 'Organization name *')}</label><input value={name} onChange={e=>{t('common.pluralSuffix', 's')}et{t('common.name', 'Name')}(e.target.value)} placeholder="Organization name"/></div>
        <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-field"><label>{t('organization{t('common.pluralSuffix', 's')}.idLabel', 'Organization ID ')}<{t('common.pluralSuffix', 's')}mall>{t('common.optional', '(optional)')}</{t('common.pluralSuffix', 's')}mall></label><input value={organizationId} onChange={e=>{t('common.pluralSuffix', 's')}etOrganizationId(e.target.value)} placeholder="{t('organization{t('common.pluralSuffix', 's')}.idPlaceholder', 'Generated from name')}"/></div>
        <div {t('common.pluralSuffix', 's')}tyle={{di{t('common.pluralSuffix', 's')}play:'flex',alignItem{t('common.pluralSuffix', 's')}:'end'}}><button cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-primary" type="button" di{t('common.pluralSuffix', 's')}abled={{t('common.pluralSuffix', 's')}aving||!name.trim()} onClick={()=>void create()}><Plu{t('common.pluralSuffix', 's')} {t('common.pluralSuffix', 's')}ize={17}/>{t('organization{t('common.pluralSuffix', 's')}.create', 'Create Organization')}</button></div>
      </div>
    </div>}
    <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-grid-2">
      <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-card vop-form-card">
        <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-{t('common.pluralSuffix', 's')}ection-title"><div><h2>Tenant work{t('common.pluralSuffix', 's')}pace{t('common.pluralSuffix', 's')}</h2><p>{item{t('common.pluralSuffix', 's')}.length} {t('organization{t('common.pluralSuffix', 's')}.configured', 'configured organization')}{item{t('common.pluralSuffix', 's')}.length===1?'':'{t('common.pluralSuffix', 's')}'}.</p></div><Building2 {t('common.pluralSuffix', 's')}ize={22}/></div>
        <div {t('common.pluralSuffix', 's')}tyle={{di{t('common.pluralSuffix', 's')}play:'grid',gap:9}}>
          {item{t('common.pluralSuffix', 's')}.map(item=><button key={item.id} type="button" onClick={()=>{{t('common.pluralSuffix', 's')}etSelected(item);{t('common.pluralSuffix', 's')}et{t('common.name', 'Name')}(item.name);{t('common.pluralSuffix', 's')}et{t('organizations.plan', 'Plan')}(item.plan||'');{t('common.pluralSuffix', 's')}et{t('common.{t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')}', 'Statu{t('common.pluralSuffix', 's')}')}(item.{t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')}||'active');{t('common.pluralSuffix', 's')}etQuota{t('common.pluralSuffix', 's')}(JSON.{t('common.pluralSuffix', 's')}tringify(item.quota{t('common.pluralSuffix', 's')}||{},null,2));{t('common.pluralSuffix', 's')}etBranding(JSON.{t('common.pluralSuffix', 's')}tringify((item a{t('common.pluralSuffix', 's')} any).branding||{},null,2));{t('common.pluralSuffix', 's')}etTenantSetting{t('common.pluralSuffix', 's')}(JSON.{t('common.pluralSuffix', 's')}tringify((item a{t('common.pluralSuffix', 's')} any).{t('common.pluralSuffix', 's')}etting{t('common.pluralSuffix', 's')}||{},null,2));void loadDetail{t('common.pluralSuffix', 's')}(item.id);}} {t('common.pluralSuffix', 's')}tyle={{textAlign:'left',border:'1px {t('common.pluralSuffix', 's')}olid #e6ebf3',background:{t('common.pluralSuffix', 's')}elected?.id===item.id?'#f4f8ff':'#fff',borderRadiu{t('common.pluralSuffix', 's')}:12,padding:'12px 14px',cur{t('common.pluralSuffix', 's')}or:'pointer'}}>
            <div {t('common.pluralSuffix', 's')}tyle={{di{t('common.pluralSuffix', 's')}play:'flex',ju{t('common.pluralSuffix', 's')}tifyContent:'{t('common.pluralSuffix', 's')}pace-between',gap:12}}><{t('common.pluralSuffix', 's')}trong>{item.name}</{t('common.pluralSuffix', 's')}trong><{t('common.pluralSuffix', 's')}pan cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-chip">{item.{t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')}}</{t('common.pluralSuffix', 's')}pan></div>
            <div {t('common.pluralSuffix', 's')}tyle={{fontSize:12,color:'#7183a4',marginTop:4}}>{item.id} · {item.memberCount} active member{t('common.pluralSuffix', 's')} · {item.plan}</div>
          </button>)}
          {!item{t('common.pluralSuffix', 's')}.length&&!loading&&<div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-empty">No organization{t('common.pluralSuffix', 's')} have been configured.</div>}
        </div>
      </div>
      <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-card vop-form-card">
        {!{t('common.pluralSuffix', 's')}elected?<div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-empty"><Building2 {t('common.pluralSuffix', 's')}ize={34}/><h3>{t('organizations.selectPrompt', 'Select an organization')}</h3><p>Organization {t('common.pluralSuffix', 's')}etting{t('common.pluralSuffix', 's')}, member{t('common.pluralSuffix', 's')}hip and u{t('common.pluralSuffix', 's')}age appear here.</p></div>:
        <>
          <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-{t('common.pluralSuffix', 's')}ection-title"><div><h2>{{t('common.pluralSuffix', 's')}elected.name}</h2><p>{{t('common.pluralSuffix', 's')}elected.id}</p></div><Edit3 {t('common.pluralSuffix', 's')}ize={20}/></div>
          <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-form-grid">
            <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-field"><label>{t('common.name', 'Name')}</label><input value={name} onChange={e=>{t('common.pluralSuffix', 's')}et{t('common.name', 'Name')}(e.target.value)}/></div>
            <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-field"><label>{t('organizations.plan', 'Plan')}</label><{t('common.pluralSuffix', 's')}elect value={plan} onChange={e=>{t('common.pluralSuffix', 's')}et{t('organizations.plan', 'Plan')}(e.target.value)} di{t('common.pluralSuffix', 's')}abled={!i{t('common.pluralSuffix', 's')}Super{t('common.admin', 'Admin')}}><option value="">{t('organizations.noPlan', 'No plan')}</option>{plan{t('common.pluralSuffix', 's')}.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</{t('common.pluralSuffix', 's')}elect>{i{t('common.pluralSuffix', 's')}Super{t('common.admin', 'Admin')}&&plan{t('common.pluralSuffix', 's')}.length===0&&<{t('common.pluralSuffix', 's')}mall>Create plan{t('common.pluralSuffix', 's')} in {t('organizations.plan', 'Plan')}{t('common.pluralSuffix', 's')} &amp; Entitlement{t('common.pluralSuffix', 's')} before a{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}igning one.</{t('common.pluralSuffix', 's')}mall>}</div>
            <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-field"><label>{t('common.{t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')}', 'Statu{t('common.pluralSuffix', 's')}')}</label><{t('common.pluralSuffix', 's')}elect value={{t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')}} onChange={e=>{t('common.pluralSuffix', 's')}et{t('common.{t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')}', 'Statu{t('common.pluralSuffix', 's')}')}(e.target.value)} di{t('common.pluralSuffix', 's')}abled={!i{t('common.pluralSuffix', 's')}Super{t('common.admin', 'Admin')}}><option value="active">{t('common.active', 'Active')}</option><option value="{t('common.pluralSuffix', 's')}u{t('common.pluralSuffix', 's')}pended">Su{t('common.pluralSuffix', 's')}pended</option><option value="archived">{t('common.archived', 'Archived')}</option></{t('common.pluralSuffix', 's')}elect></div><div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-field" {t('common.pluralSuffix', 's')}tyle={{gridColumn:'1 / -1'}}><label>U{t('common.pluralSuffix', 's')}age quota{t('common.pluralSuffix', 's')} (JSON)</label><textarea value={quota{t('common.pluralSuffix', 's')}} onChange={e=>{t('common.pluralSuffix', 's')}etQuota{t('common.pluralSuffix', 's')}(e.target.value)} di{t('common.pluralSuffix', 's')}abled={!i{t('common.pluralSuffix', 's')}Super{t('common.admin', 'Admin')}} row{t('common.pluralSuffix', 's')}={4} placeholder='{"maxU{t('common.pluralSuffix', 's')}er{t('common.pluralSuffix', 's')}":100,"maxGuide{t('common.pluralSuffix', 's')}":20,"maxQuizze{t('common.pluralSuffix', 's')}":100,"maxAnnouncement{t('common.pluralSuffix', 's')}":50,"maxRadioItem{t('common.pluralSuffix', 's')}":50,"maxMaterial{t('common.pluralSuffix', 's')}":100}'/><{t('common.pluralSuffix', 's')}mall>Leave a limit out, or u{t('common.pluralSuffix', 's')}e a negative value, for unlimited. Limit{t('common.pluralSuffix', 's')} are enforced {t('common.pluralSuffix', 's')}erver-{t('common.pluralSuffix', 's')}ide when the organization create{t('common.pluralSuffix', 's')} new record{t('common.pluralSuffix', 's')}.</{t('common.pluralSuffix', 's')}mall></div>
            <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-field"><label>{t('organizations.tenantBranding', 'Tenant branding (JSON)')}</label><textarea value={branding} onChange={e=>{t('common.pluralSuffix', 's')}etBranding(e.target.value)} row{t('common.pluralSuffix', 's')}={4} placeholder='{"logoUrl":"","primaryColor":"","accentColor":"","app{t('common.name', 'Name')}":""}'/><{t('common.pluralSuffix', 's')}mall>Branding belong{t('common.pluralSuffix', 's')} to thi{t('common.pluralSuffix', 's')} organization and i{t('common.pluralSuffix', 's')} re{t('common.pluralSuffix', 's')}olved from tenant configuration.</{t('common.pluralSuffix', 's')}mall></div>
            <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-field"><label>Tenant {t('common.pluralSuffix', 's')}etting{t('common.pluralSuffix', 's')} (JSON)</label><textarea value={tenantSetting{t('common.pluralSuffix', 's')}} onChange={e=>{t('common.pluralSuffix', 's')}etTenantSetting{t('common.pluralSuffix', 's')}(e.target.value)} row{t('common.pluralSuffix', 's')}={4} placeholder='{"timezone":"Africa/Lu{t('common.pluralSuffix', 's')}aka","defaultUiLocale":"en"}'/><{t('common.pluralSuffix', 's')}mall>Organization-{t('common.pluralSuffix', 's')}pecific runtime {t('common.pluralSuffix', 's')}etting{t('common.pluralSuffix', 's')}. Do not place {t('common.pluralSuffix', 's')}ecret{t('common.pluralSuffix', 's')} here.</{t('common.pluralSuffix', 's')}mall></div>
            <div {t('common.pluralSuffix', 's')}tyle={{di{t('common.pluralSuffix', 's')}play:'flex',alignItem{t('common.pluralSuffix', 's')}:'end'}}><button cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-primary" type="button" di{t('common.pluralSuffix', 's')}abled={{t('common.pluralSuffix', 's')}aving} onClick={()=>void {t('common.pluralSuffix', 's')}ave()}>Save Setting{t('common.pluralSuffix', 's')}</button></div>
          </div>
          {analytic{t('common.pluralSuffix', 's')}&&<div {t('common.pluralSuffix', 's')}tyle={{marginTop:16}}><div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-{t('common.pluralSuffix', 's')}ection-title"><div><h3>Tenant analytic{t('common.pluralSuffix', 's')}</h3><p>Aggregated only from thi{t('common.pluralSuffix', 's')} organization'{t('common.pluralSuffix', 's')} tenant-{t('common.pluralSuffix', 's')}coped record{t('common.pluralSuffix', 's')}.</p></div><BarChart3 {t('common.pluralSuffix', 's')}ize={20}/></div><div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-grid-3"><div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-card vop-mini-{t('common.pluralSuffix', 's')}tat"><U{t('common.pluralSuffix', 's')}er{t('common.pluralSuffix', 's')} {t('common.pluralSuffix', 's')}ize={20}/><div><{t('common.pluralSuffix', 's')}trong>{analytic{t('common.pluralSuffix', 's')}.member{t('common.pluralSuffix', 's')}}</{t('common.pluralSuffix', 's')}trong><{t('common.pluralSuffix', 's')}pan>{t('common.active', 'Active')} member{t('common.pluralSuffix', 's')}</{t('common.pluralSuffix', 's')}pan></div></div><div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-card vop-mini-{t('common.pluralSuffix', 's')}tat"><BookOpen {t('common.pluralSuffix', 's')}ize={20}/><div><{t('common.pluralSuffix', 's')}trong>{analytic{t('common.pluralSuffix', 's')}.content.le{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}on{t('common.pluralSuffix', 's')}||0}</{t('common.pluralSuffix', 's')}trong><{t('common.pluralSuffix', 's')}pan>Le{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}on{t('common.pluralSuffix', 's')}</{t('common.pluralSuffix', 's')}pan></div></div><div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-card vop-mini-{t('common.pluralSuffix', 's')}tat"><Award {t('common.pluralSuffix', 's')}ize={20}/><div><{t('common.pluralSuffix', 's')}trong>{analytic{t('common.pluralSuffix', 's')}.content.certificate{t('common.pluralSuffix', 's')}||0}</{t('common.pluralSuffix', 's')}trong><{t('common.pluralSuffix', 's')}pan>Certificate{t('common.pluralSuffix', 's')}</{t('common.pluralSuffix', 's')}pan></div></div></div><div {t('common.pluralSuffix', 's')}tyle={{di{t('common.pluralSuffix', 's')}play:'flex',gap:8,flexWrap:'wrap',marginTop:10}}>{Object.entrie{t('common.pluralSuffix', 's')}(analytic{t('common.pluralSuffix', 's')}.roleCount{t('common.pluralSuffix', 's')}).map(([role,count])=><{t('common.pluralSuffix', 's')}pan key={role} cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-chip">{role}: {count}</{t('common.pluralSuffix', 's')}pan>)}</div></div>}
          {u{t('common.pluralSuffix', 's')}age&&<div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-grid-3" {t('common.pluralSuffix', 's')}tyle={{marginTop:16}}>
            <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-card vop-mini-{t('common.pluralSuffix', 's')}tat"><U{t('common.pluralSuffix', 's')}er{t('common.pluralSuffix', 's')} {t('common.pluralSuffix', 's')}ize={20}/><div><{t('common.pluralSuffix', 's')}trong>{u{t('common.pluralSuffix', 's')}age.member{t('common.pluralSuffix', 's')}}</{t('common.pluralSuffix', 's')}trong><{t('common.pluralSuffix', 's')}pan>Member{t('common.pluralSuffix', 's')}</{t('common.pluralSuffix', 's')}pan></div></div>
            <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-card vop-mini-{t('common.pluralSuffix', 's')}tat"><BarChart3 {t('common.pluralSuffix', 's')}ize={20}/><div><{t('common.pluralSuffix', 's')}trong>{u{t('common.pluralSuffix', 's')}age.guide{t('common.pluralSuffix', 's')}}</{t('common.pluralSuffix', 's')}trong><{t('common.pluralSuffix', 's')}pan>Guide{t('common.pluralSuffix', 's')}</{t('common.pluralSuffix', 's')}pan></div></div>
            <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-card vop-mini-{t('common.pluralSuffix', 's')}tat"><Shield {t('common.pluralSuffix', 's')}ize={20}/><div><{t('common.pluralSuffix', 's')}trong>{u{t('common.pluralSuffix', 's')}age.quizze{t('common.pluralSuffix', 's')}}</{t('common.pluralSuffix', 's')}trong><{t('common.pluralSuffix', 's')}pan>Quizze{t('common.pluralSuffix', 's')}</{t('common.pluralSuffix', 's')}pan></div></div>
          </div>}
          <div {t('common.pluralSuffix', 's')}tyle={{marginTop:18}}>
            <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-{t('common.pluralSuffix', 's')}ection-title"><div><h3>Audit hi{t('common.pluralSuffix', 's')}tory</h3><p>Privileged organization change{t('common.pluralSuffix', 's')} are retained a{t('common.pluralSuffix', 's')} append-only record{t('common.pluralSuffix', 's')}.</p></div></div>
            <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-table-wrap"><table cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-table"><thead><tr><th>{t('common.action', 'Action')}</th><th>{t('common.target', 'Target')}</th><th>{t('common.actor', 'Actor')}</th><th>{t('common.time', 'Time')}</th></tr></thead><tbody>{audit.map(item=><tr key={String(item.id)}><td>{String(item.action||'')}</td><td>{String(item.target||'')}</td><td>{String(item.actor{t('common.email', 'Email')}||item.actorUid||'')}</td><td>{item.time{t('common.pluralSuffix', 's')}tamp && typeof item.time{t('common.pluralSuffix', 's')}tamp==='object' ? '{t('common.recorded', 'Recorded')}' : String(item.time{t('common.pluralSuffix', 's')}tamp||'')}</td></tr>)}</tbody></table>{!audit.length&&<div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-empty">No privileged change{t('common.pluralSuffix', 's')} have been recorded.</div>}</div>
          </div>
          <div {t('common.pluralSuffix', 's')}tyle={{marginTop:18}}>
            <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-{t('common.pluralSuffix', 's')}ection-title"><div><h3>{t('organizations.inviteMember', 'Invite a member')}</h3><p>Send a {t('common.pluralSuffix', 's')}ecure invitation that expire{t('common.pluralSuffix', 's')} after {t('common.pluralSuffix', 's')}even day{t('common.pluralSuffix', 's')}.</p></div></div>
            <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-form-grid">
              <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-field"><label>{t('common.email', 'Email')} *</label><input type="email" value={invite{t('common.email', 'Email')}} onChange={e=>{t('common.pluralSuffix', 's')}etInvite{t('common.email', 'Email')}(e.target.value)} placeholder="member@example.org"/></div>
              <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-field"><label>{t('common.role', 'Role')}</label><{t('common.pluralSuffix', 's')}elect value={invite{t('common.role', 'Role')}} onChange={e=>{t('common.pluralSuffix', 's')}etInvite{t('common.role', 'Role')}(e.target.value)}><option value="learner">{t('common.learner', 'Learner')}</option><option value="mentor">{t('common.mentor', 'Mentor')}</option><option value="teacher">{t('common.teacher', 'Teacher')}</option><option value="editor">{t('common.editor', 'Editor')}</option><option value="admin">{t('common.admin', 'Admin')}</option><option value="viewer">{t('common.viewer', 'Viewer')}</option></{t('common.pluralSuffix', 's')}elect></div>
              <div {t('common.pluralSuffix', 's')}tyle={{di{t('common.pluralSuffix', 's')}play:'flex',alignItem{t('common.pluralSuffix', 's')}:'end'}}><button cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-{t('common.pluralSuffix', 's')}econdary" type="button" di{t('common.pluralSuffix', 's')}abled={{t('common.pluralSuffix', 's')}aving||!invite{t('common.email', 'Email')}.trim()} onClick={()=>void invite()}><U{t('common.pluralSuffix', 's')}er{t('common.pluralSuffix', 's')} {t('common.pluralSuffix', 's')}ize={16}/>{t('organizations.createInvitation', 'Create Invitation')}</button></div>
            </div>
            {inviteUrl&&<div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-{t('common.pluralSuffix', 's')}etting-row" {t('common.pluralSuffix', 's')}tyle={{marginTop:10}}><div><div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-{t('common.pluralSuffix', 's')}etting-name">{t('organizations.invitationLink', 'Invitation link')}</div><div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-{t('common.pluralSuffix', 's')}etting-help">Share thi{t('common.pluralSuffix', 's')} {t('common.pluralSuffix', 's')}ingle-u{t('common.pluralSuffix', 's')}e link with the invited u{t('common.pluralSuffix', 's')}er.</div></div><button cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-{t('common.pluralSuffix', 's')}econdary" type="button" onClick={()=>void navigator.clipboard?.writeText(inviteUrl)}><Check {t('common.pluralSuffix', 's')}ize={16}/>{t('common.copy', 'Copy Link')}</button></div>}
          </div>
          <div {t('common.pluralSuffix', 's')}tyle={{marginTop:18}}>
            <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-{t('common.pluralSuffix', 's')}ection-title"><div><h3>Member{t('common.pluralSuffix', 's')}hip</h3><p>A{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}ign an exi{t('common.pluralSuffix', 's')}ting account to thi{t('common.pluralSuffix', 's')} organization.</p></div></div>
            <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-form-grid">
              <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-field"><label>U{t('common.pluralSuffix', 's')}er UID *</label><input value={memberUid} onChange={e=>{t('common.pluralSuffix', 's')}etMemberUid(e.target.value)} placeholder="Fireba{t('common.pluralSuffix', 's')}e account UID"/></div>
              <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-field"><label>{t('common.role', 'Role')}</label><{t('common.pluralSuffix', 's')}elect value={member{t('common.role', 'Role')}} onChange={e=>{t('common.pluralSuffix', 's')}etMember{t('common.role', 'Role')}(e.target.value)}><option value="learner">{t('common.learner', 'Learner')}</option><option value="mentor">{t('common.mentor', 'Mentor')}</option><option value="teacher">{t('common.teacher', 'Teacher')}</option><option value="editor">{t('common.editor', 'Editor')}</option><option value="admin">{t('common.admin', 'Admin')}</option></{t('common.pluralSuffix', 's')}elect></div>
              <div {t('common.pluralSuffix', 's')}tyle={{di{t('common.pluralSuffix', 's')}play:'flex',alignItem{t('common.pluralSuffix', 's')}:'end'}}><button cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-{t('common.pluralSuffix', 's')}econdary" type="button" di{t('common.pluralSuffix', 's')}abled={{t('common.pluralSuffix', 's')}aving||!memberUid.trim()} onClick={()=>void addMember()}><U{t('common.pluralSuffix', 's')}er{t('common.pluralSuffix', 's')} {t('common.pluralSuffix', 's')}ize={16}/>A{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}ign</button></div>
            </div>
            <div cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-table-wrap" {t('common.pluralSuffix', 's')}tyle={{marginTop:12}}><table cla{t('common.pluralSuffix', 's')}{t('common.pluralSuffix', 's')}{t('common.name', 'Name')}="vop-table"><thead><tr><th>UID</th><th>{t('common.role', 'Role')}</th><th>{t('common.{t('common.pluralSuffix', 's')}tatu{t('common.pluralSuffix', 's')}', 'Statu{t('common.pluralSuffix', 's')}')}</th></tr></thead><tbody>{member{t('common.pluralSuffix', 's')}.map(item=><tr key={item.uid}><td>{item.uid}</td><td>{item.role}</td><td>{item.active?'{t('common.active', 'Active')}':'Inactive'}</td></tr>)}</tbody></table></div>
          </div>
        </>}
      </div>
    </div>
  </div>;
}
